### ISSUE TITLE
Use composer.lock (or installed.json) for package discovery

### ISSUE THREAD

**Issue by jtheuerkauf** [tempestphp/tempest-framework#117]
https://github.com/tempestphp/tempest-framework/blob/b983830f37ea6293eb602c5768fb1c251f5195d8/src/Application/Kernel.php#L76

i'm examining the lock JSON from another project, and i see that every entry in the root `composer.json` includes the packages each _dependency_ requires. So why not use that already compiled list?

The expectations are the same as the original, with some key differences:

* Read ONE file with the added expectation that `composer install|update` is locked. Since that's the most common approach, especially in production, it seems like a good primary strategy.
* For a no-lock, you could fall back to reading the `autoload_psr4.php` file and all the packages' `composer.json` files.
* The lock file can be pretty large, so stuffing it all into a simple array is probably not the best. Perhaps look for an alternative data loading method?

Just a rough sketch of what *might* work:

```php
private function initDiscoveryLocations(): void
{
    if (is_file(path($this->root . '/composer.lock'))) {
        // WARN: Is there a more memory-efficient way to load and access the JSON?
        $lockContent = file_get_contents(path($this->root, 'composer.lock'));
        $composer = json_decode($lockContent, true);

        foreach ($composer['packages'] ?? [] as $package) {
            // WARN: Is this universally true? Does the package name ALWAYS match the "vendor/___" path?
            $packagePath = path($this->root, 'vendor', $package['name']);

            // Tempest must be required by the package, and must define PSR-4 namespace map
            if (isset($package['require']['tempest/framework'], $package['autoload']['psr-4'])
                && is_array($package['autoload']['psr-4'])
            ) {
                foreach ($package['autoload']['psr-4'] as $namespace => $pkgNamespacePath) {
                    $this->appConfig->discoveryLocations[] = new DiscoveryLocation(
                        namespace: $namespace,
                        path: path($packagePath, $pkgNamespacePath),
                    );
                }
            }
        }
    } else {
        // Do the existing logic?
    }
}
```

**Comment by aidan-casey** [comment]
Yeah, I was look at this too. You can also use `vendor/composer/installed.json`. I wish that `vendor/composer/installed.php` had the same info! 🙂 

The problem is it will always be slower because you have to use `json_decode` vs. `str_contains`.

I started to mess around last night with using regex to do this, but it's not an easy pattern to match.

**Comment by jtheuerkauf** [comment]
Oh hey! `installed.json` is a lot lighter than the lock file, for sure. Didn't notice that was there. Looks like it has the same info needed for this. Good catch.

What are you trying to match with regex? Isn't it the Tempest package name (`tempest/framework`)? Since the package name is a key in the package's `require` object, you shouldn't need to pattern match...

```json
{
    "packages": [
        {
            "name": "cycle/annotated",
            "require": {
                "cycle/orm": "^2.7",
                "...": "..."
            },
            "autoload": {
                "psr-4": {
                    "Cycle\\Annotated\\": "src/"
                }
            }
        }
    ]
}
```

Given that sample from the project i was examining... In our situation, the JSON would look like this:
```json
{
    "packages": [
        {
            "name": "cycle/annotated",
            "require": {
                "tempest/framework": "0.0.1-alpha",
                "...": "..."
            },
            "autoload": {
                "psr-4": {
                    "Cycle\\Annotated\\": "src/"
                }
            }
        }
    ]
}
```
Am i missing something where `"tempest/framework"` might be something different, or that i'm looking at the wrong thing to discover the dependency?

**Comment by aidan-casey** [comment]
@jtheuerkauf - This is what I was playing with last night. I _think_ it would suffice, but it needs further testing.

```regex
(?<="tempest\/\w*"[\s\S]*)(?<!\s{8}\})(?<="install-path": )[\S]*
```

**Comment by jtheuerkauf** [comment]
@aidan-casey 
> ```regexp
> /(?<="tempest\/\w*"[\s\S]*)(?<!\s{8}\})(?<="install-path": )[\S]*/
> ```

Can you show a sample of JSON where this is attempting to match something?

**Comment by brendt** [comment]
So, we could use `composer.lock` or `installed.json` instead of scanning the whole vendor directory, but composer.lock is much larger, especially if we have to load all of it in memory because we have to decode the json. 

I wouldn't go the regex route, whether it's faster or not btw @aidan-casey, I think that's a rabbit hole we don't want to venture it, looking at it from the maintainer's perspective 😅

A couple of ideas:

- We should benchmark it, compare the current implementation vs a naive `json_decode` on `installed.json`. We need to compare execution time and memory usage. Maybe we're making a big deal out of nothing, and this new approach is much faster. We should make sure not to compare absolute numbers, but take note of the relative difference, and we should make sure we have enough dummy dependencies, 20-30 packages isn't uncommon for real life projects.
- Let's say `json_decode` on installed.json is promising, but it uses too much memory. What if we approach it slightly different? This file is essentially a JSON array, what if we manually split that JSON text into each individual entry, and then call `json_decode` on each entry separately, I can image that would have a positive impact on memory usage, but might have a slightly negative impact on CPU usage. It might be an interesting one to benchmark.
- Are we sure `installed.json` will always be available? It probably will be though, my guess is that composer uses it internally.

**Comment by brendt** [comment]
btw, super cool idea @jtheuerkauf, thanks! Are you up for doing some more digging into this, or should I take over?

**Comment by aidan-casey** [comment]
@brendt - I have benchmark numbers on json_decode vs. the current implementation. We are essentially talking `0.009` vs. `0.005`.

**Comment by aidan-casey** [comment]
As far as regex goes... I was so close though! 🙃

**Comment by brendt** [comment]
> I have benchmark numbers on json_decode vs. the current implementation. We are essentially talking 0.009 vs. 0.005.

Ok so, `json_decode` is slower in your benchmark? A couple things we need to consider: 

- Have you tried with 20-30 additional packages? 
- Have you considered the splitting method? 

It looks like @jtheuerkauf want to do some digging 👍 Let's give it a try, but let's keep in mind that the outcome might very well be that we'll keep the current implementation :)

**Comment by aidan-casey** [comment]
So in my benchmarks, I've been requiring `laravel/framework` (the irony I know!) to add a decent amount of packages in. I think the highest I have seen the current implementation get to was `0.007`, but `json_decode` gets slower the larger the file is.

I have considered splitting based on `/\s{8}\{/` and `/\s{8}\}/` , but have not done any testing with that. Happy for @jtheuerkauf to do some digging, just throwing out what I was playing with for reference. 🙂

**Comment by jtheuerkauf** [comment]
> So, we could use `composer.lock` or `installed.json` instead of scanning the whole vendor directory, but composer.lock is much larger, especially if we have to load all of it in memory because we have to decode the json.

i'm definitely in favor of `installed.json` now that i know it exists. i'm _fairly_ sure composer generates it internally, so it should always be available. i don't know of any command option to skip it (as is the case with `--no-lock`).

> A couple of ideas:
> 
>     * We should benchmark it, compare the current implementation vs a naive `json_decode` on `installed.json`. We need to compare execution time and memory usage. Maybe we're making a big deal out of nothing, and this new approach is much faster. We should make sure not to compare absolute numbers, but take note of the relative difference, and we should make sure we have enough dummy dependencies, 20-30 packages isn't uncommon for real life projects.

i'm not a benchmark expert, so some guidance here would be appreciated. Maybe i should just write the working code and we can test it once it's pushed?

>     * Let's say `json_decode` on installed.json is promising, but it uses too much memory. What if we approach it slightly different? This file is essentially a JSON array, what if we manually split that JSON text into each individual entry, and then call `json_decode` on each entry separately, I can image that would have a positive impact on memory usage, but might have a slightly negative impact on CPU usage. It might be an interesting one to benchmark.

i'm not sure i follow here... How do you break up a text file into "individual entries"? i wish there were a way to read JSON from a file into a generator. Seems like that would be fantastic to save memory. Is there?

**Comment by jtheuerkauf** [comment]
@brendt Do you want me to fork, or clone straight from here?

**Comment by aidan-casey** [comment]
@jtheuerkauf I have been using the following for benchmarking:

```php
    private function initDiscoveryLocations(): void
    {
        $startup = microtime(true);

        $namespaces = require path($this->root, '/vendor/composer/autoload_psr4.php');

        foreach ($namespaces as $namespace => $path) {
            $composer = @file_get_contents(path($path[0], '/../composer.json'));

            if (! $composer) {
                continue;
            }

            if (str_contains($composer, '"tempest/framework"')) {
                $this->appConfig->discoveryLocations[] = new DiscoveryLocation(
                    namespace: $namespace,
                    path: $path[0],
                );
            }
        }

        die(microtime(true) - $startup);
    }
```

For what it is worth, running the current implementation on PHP 8.3 _without_ Laravel in the dependencies it's actually coming in around `0.0009` for me now.

For splitting, if you match on 8 characters of whitespace plus 1 curly brace ({) you can reasonably use preg_split to break up the file. I'm not sure that's going to help us out much here, but worth trying.

**Comment by aidan-casey** [comment]
Now that I think about it, you might be able to refine that `preg_split` to require it includes `tempest/*`. That would reduce the number of times you need to json_decode depending on how many packages you install.

**Comment by brendt** [comment]
> Do you want me to fork, or clone straight from here?

You can clone, but you'll need a fork if you want to submit a PR, so forking is better ;)

**Comment by jtheuerkauf** [comment]
@brendt / @aidan-casey 
I added Aidan's `microtime()`s to the discovery function and ran with both versions of the discovery logic:

Original:
```
$ for ((i = 0; i < 10; i++)); do php tempest; done

0.35448598861694
0.34615898132324
0.33336806297302
0.36861801147461
0.34600281715393
0.37153315544128
0.37795615196228
0.3643639087677
0.31627607345581
0.43297719955444

(Avg: 0.361 sec)
```

Read `installed.json` with plain `json_decode()`:
```
$ for ((i = 0; i < 10; i++)); do php tempest; done

0.12407517433167
0.14981889724731
0.11219000816345
0.11968398094177
0.11466193199158
0.11280298233032
0.1087110042572
0.14143085479736
0.1223349571228
0.11647009849548

(Avg: 0.122 sec)
```

Pretty significant improvement. The difference, however, is `installed.json` doesn't have the ROOT requirements (y'know, namespaces defined by the framework itself...).

So, if i add parsing `./composer.json` i'll get those namespaces.

Result:
```
$ for ((i = 0; i < 10; i++)); do php tempest; done
0.15885615348816
0.12874913215637
0.21586585044861
0.19676804542542
0.13530588150024
0.13356399536133
0.13014984130859
0.11175990104675
0.11767983436584
0.15792989730835

(Avg: 0.148 sec)
```
Barely noticeable increase.

---

i'll submit what i've got so we can start a review for any refinements it needs.

---

One additional thought: the original is only looking at PSR-4 namespaces. Since this change now looks at the `"autoload"` keys, do you have any desire to include PSR-0? My vote would be no, but it's your framework. 😁

**Comment by aidan-casey** [comment]
@jtheuerkauf - Just a couple quick thoughts...

1. Unless you are otherwise disabling caching, can you revise your benchmark slightly to run `php tempest discovery:clear` prior to the test?
2. Have you installed some hefty packages into the environment to trigger some larger composer files? (e.g., `laravel/framework`, `symfony/symfony`, etc.)

Personally, I'd be inclined to support all autoloading methods composer does, but I think we are going to have other refactoring required for that and I suspect @brendt might disagree with me on that one. 🙂

**Comment by aidan-casey** [comment]
Oh! One other thing...

What do you come in at if you run a `preg_match_all` with a pattern to split out each package json? A pattern like the following should get you there:

```regex
/(?<=\s{8})\{[\s\S]+?\n\s{8}\}/
```

**Comment by jtheuerkauf** [comment]
`DISCOVERY_CACHE=false` in `.env`, so caching is off, yes?

---

i'll post my code so you can show me where/how i should attempt the regex approach. i'm not sure i follow what it's attempting to do.

**Comment by aidan-casey** [comment]
Yup, caching should be off then.

Feel free to post a snippet and we can take a look!

**Comment by jtheuerkauf** [comment]
@aidan-casey / @brendt PR posted. #125

**Comment by aidan-casey** [comment]
Thanks, @jtheuerkauf! Left a comment with what I was thinking. Just curious what the benchmark would come out to. 🙂

**Comment by brendt** [comment]
@aidan-casey can't let go of his regexes 😅

This looks promising, we'll continue the discussion in the PR

**Comment by aidan-casey** [comment]
Two things...

1. RegEx is under utilized because people like @brendt are scared of it. 🙃 
2. I spent a lot of time refining that one Tuesday. 😅
