### ISSUE TITLE
Add Session Support

### ISSUE THREAD

**Issue by aidan-casey** [tempestphp/tempest-framework#123]
It would be good to support sessions in Tempest. The way I see it, we have two options for this:

1. Session interface that different session storage types can implement.
2. Session storage interface that gets passed a session class owned by Tempest. This solution allows us to offer some "ease of access" items, such as dot notation, if we desire.

Any thoughts, @brendt?

**Comment by brendt** [comment]
My thoughts:

- Indeed we need session support, related to #113 and #10 
- Makes sense to build in support for multiple drivers, although I'd only support PHP's built-in session storage for now
- Dot notation is out of scope for this specific feature I believe

**Comment by aidan-casey** [comment]
Not so much harping on dot notation as using it as an example of why we might want to wrap drivers instead of swap using interfaces.

Question really just comes down to whether you swap the session driver by registering a different implementation in the container, or changing (in a config or elsewhere) the driver passed to a global session class.

**Comment by brendt** [comment]
That's a good question that will need some further looking into when we tackle this problem (the same question is there for the event bus as well)

**Comment by aidan-casey** [comment]
Okay, so I have been doing some work on this and I have some thoughts. Wanted to run this by you, @brendt.

First, different frameworks are handling this differently:

**Symfony**
- Has a master `Session` class for interacting with the session.
- Has a `SessionStorage` class for various types of storage.
- Has a `NativeSessionStorage` which utilizes PHP's built-in `SessionHandlerInterface` and one of their many `SessionHandlerInterface` implementations. 
- Has several other `SessionStorage` implementations such as array, file, etc.

**Laravel**
- Utilizes PHP's built-in `SessionHandlerInterface`.
- Does allow sessions to be encrypted by using the `EncryptedStore`.

---

I believe the absolute best way to handle this is by having a single `Session` class which accepts a `SessionHandlerInterface` implementation. This class acts as a wrapper around PHP's built-in session functions and sets up the session handler for reading/writing the session.

The question becomes what to do with the idea of encrypting a session. We have a few options I can think of.

1. Accept as a second parameter to the `Session` class a `SessionSerializer` implementation that can serialize and unserialize a session. The problem with this approach is that now we are adding serialization on top of PHP's native serialization, but it probably is the cleanest approach.
2. Allow the registration of session "middleware" which are all passed the session array prior to writing it. An encryption middleware could handle the serialization of the array and encryption of the string.
3. Simply have an `EncryptedSessionHandler` that implements the `SessionHandlerInterface` and accepts a `SessionHandlerInterface` in the construct. This then handles the encryption of the string and then passes it off to the other `SessionHandlerInterface`. This seems like the worst option to me since it requires the implementation of several unnecessary methods.

**Comment by brendt** [comment]
> I believe the absolute best way to handle this is by having a single Session class which accepts a SessionHandlerInterface implementation. This class acts as a wrapper around PHP's built-in session functions and sets up the session handler for reading/writing the session.

Agree

> Accept as a second parameter to the Session class a SessionSerializer implementation that can serialize and unserialize a session. The problem with this approach is that now we are adding serialization on top of PHP's native serialization, but it probably is the cleanest approach.

Agree, I don't mind writing something on top of PHP's native parts if it makes things easier

See, as long as no one mentions PSR,  there's only agreement 😁

---

For convenience, I'd like to see methods on `Request` and `Response` as well. Internally they are allowed to use service location to access `Session`.

**Comment by brendt** [comment]
We'll do some more refactoring in #206
