### ISSUE TITLE
Returning view models with additional response data

### ISSUE THREAD

**Issue by brendt** [tempestphp/tempest-framework#128]
Controllers can return views or view models directly: 

```php
    #[Get(uri: '/')]
    public function __invoke(): View
    {
        return new HomeView(
            name: 'Brent',
        );
    }
```

This logic happens in the router:

```php
    private function createResponse(Response|View $input): Response
    {
        if ($input instanceof View) {
            return response($input->render($this->appConfig));
        }

        return $input;
    }
```

First of all, the router shouldn't be concerned with doing this, I suggest to move this logic to the `ResponseSender` once that's merged (#100). We also need to find a way to access the response object from within the view to modify it, eg. to send headers.

**Comment by brendt** [comment]
@aidan-casey , would love your input, especially on the second part about getting access to the response.

**Comment by aidan-casey** [comment]
Let me think on this for a bit. I feel like the router should be returning a response and the sender should simply be sending one, but I'm not sure where that puts this.

**Comment by aidan-casey** [comment]
@brendt - I am still assembling my thoughts, but I _think_ they basically boil down to this:

1. The implementation of a response factory. The response factory's only goal is to eventually boil everything down to plain text and return a response object. The router is only concerned about about getting that response object.
2. The implementation of a view renderer. Somehow (unsure yet how) this can determine different types of views (markdown, html, etc.) and pass them to the correct driver. These then convert the template to plain text.

Not sure if that makes sense or not. 😛

**Comment by brendt** [comment]
So, a couple of options:

## 1. Have `View` extend `Response`

```
#[Get('/view-model-with-response-data')]
public function viewModelWithResponseData(): View
{
    return (new ViewModelWithResponseData())
        ->header('x-from-viewmodel', 'true')
        ->status(Status::CREATED);
}
```

Pros:

- Technically, a `View` _is_ a specialised form of a `Response`, at leas the way we deal with them in Tempest
- You get access to all `Response` methods on the `View` directly

Cons:

- It might feel weird and incorrect

## 2. `View` implements their own `header` and `status` methods

We'll copy over this data to the response when creating the response

```php
#[Get('/view-model-with-response-data')]
public function viewModelWithResponseData(): View
{
    return (new ViewModelWithResponseData())
        ->header('x-from-viewmodel', 'true')
        ->status(Status::CREATED);
}
```

Pros:

- We can keep the same public API as the first example
- I might feel more correct to people who felt the first option isn't correct

Cons:

- Code duplication between `Response` and `View`

## 3. Introduce a way to convert the `View` to a `Response` within the controller

This way we can return a response, and we have access to everything. There are several ways of doing so.

A `view` function takes a `View` and returns a `Response`:

```php
return view(new ViewModelWithResponseData())
    ->header('x-from-viewmodel', 'true')
    ->status(Status::CREATED);
```

A `toResponse` method on the `View`:

```php
return (new ViewModelWithResponseData())
    ->toResponse()
    ->header('x-from-viewmodel', 'true')
    ->status(Status::CREATED);
```

Or a factory:

```php
#[Get('/view-model-with-response-data')]
public function viewModelWithResponseData(ResponseFactory $factory): View
{
    return $factory->make(new ViewModelWithResponseData())
        ->header('x-from-viewmodel', 'true')
        ->status(Status::CREATED);
}
```

Pros:

- Complete separation between `View` and `Response`, which might feel more correct
- We could make it so that controllers may only return `Response` objects, leading to less available ways to do something

Cons:

- It's more verbose, you need _two_ steps to returning a ViewModel
- In both the `view()` and `toResponse()` options, we'll need to rely on service location to actually render the view (it needs access to `AppConfig`. The `ResponseFactory` option doesn't have this problem, but feels even more verbose.

**Comment by brendt** [comment]
A very good argument on Twitter: https://twitter.com/_Geelik_/status/1764571588425396505

"A view can be used in other contexts as well, eg. for mails"

**Comment by brendt** [comment]
```
return response()
       ->status(Status::CREATED)
       ->header('x-from-viewmodel', 'true')
       ->view(new ViewModelWithResponseData());
```

This is the perfect solution. Thanks @aidan-casey 😅

**Comment by brendt** [comment]
Fixed.
