### ISSUE TITLE
Don't die on missing .env

### ISSUE THREAD

**Issue by aidan-casey** [tempestphp/tempest-framework#130]
It is entirely valid to load environment variables from the system and will commonly done with things like Docker. I'm not sure we should be preventing the application from loading without the `.env` file.

**Comment by alibori** [comment]
Hi @aidan-casey !

what you are proposing is to remove the `die` block from the `catch`?

```php
try {
    $dotenv = Dotenv::createUnsafeImmutable($root);
    $dotenv->load();
} catch (InvalidPathException) {
    die("Missing .env file in {$root}" . PHP_EOL);
}
```

**Comment by aidan-casey** [comment]
Yup!

**Comment by sanderdlm** [comment]
This is supported out of the box by the package you're using. You can do
```php
$dotenv = Dotenv::createUnsafeImmutable($root);
$dotenv->loadSafe();
```
See https://github.com/vlucas/phpdotenv README.

**Comment by aidan-casey** [comment]
I thought I recalled there being a method for this. Thank you!

**Comment by brendt** [comment]
Just as a sidenote: what a confusing API 🙃

```
createUnsafeImmutable
loadSafe
```

We're creating unsafe immutable… what exactly? And then we're safe loading the unsafe stuff? 🤯
