### ISSUE TITLE
Catch validation exceptions in the router

### ISSUE THREAD

**Issue by brendt** [tempestphp/tempest-framework#14]

**Comment by brendt** [comment]
I don't remember what I thought when I created this issue, but I'm pretty sure this isn't the way I want to do it anymore. Will look into it later

**Comment by aidan-casey** [comment]
<img width="402" alt="Screenshot 2024-02-23 at 2 52 57 PM" src="https://github.com/tempestphp/tempest-framework/assets/6686277/8528c09a-ae01-4381-8353-130cdce5dfbc">
