### ISSUE TITLE
Request handling is a bit... broken

### ISSUE THREAD

**Issue by aidan-casey** [tempestphp/tempest-framework#158]
In the process of building out #153, I've found that request handling is a tad broken. Below are some problems I have found.

1. Headers do not appear to be set.
2. The request body is not set and is currently typed as an array, which should probably be a string.
3. The http application is what is building up the request. This is fine, but does create a little extra work for setting up a testing request. Laravel/Symfony pass the request to the http kernel. Maybe worth discussing?

**Comment by brendt** [comment]
> Headers do not appear to be set.

That's now fixed

> The request body is not set and is currently typed as an array, which should probably be a string.

Also fixed now, although why should it be a string? `$_GET` and `$_POST` are already arrays, I'd keep it that way.

> The http application is what is building up the request. This is fine, but does create a little extra work for setting up a testing request. Laravel/Symfony pass the request to the http kernel. Maybe worth discussing?

I think we discussed this as well in one or two PRs and believe we've found a solution for it 👍

I'm gonna close this one, but feel free to reopen if I've missed anything
