### ISSUE TITLE
Create distinction between integration and unit tests

### ISSUE THREAD

**Issue by aidan-casey** [tempestphp/tempest-framework#171]
@brendt - I am thinking we should create an distinction between integration and unit tests for the framework. Unit tests would only ever extend `PHPUnit\Framework\TestCase` while integration tests might extend `Tempest\Testing\TestCase`. We could even add architecture tests for this to ensure each directory is being used appropriately.

Any objections to this?

**Comment by brendt** [comment]
Sounds perfect 👍
