### ISSUE TITLE
PHPStan Rule Levels

### ISSUE THREAD

**Issue by aidan-casey** [tempestphp/tempest-framework#186]
We are currently operating on PHPStan [rule level](https://phpstan.org/user-guide/rule-levels) 0 (this lowest possible level). We should be working toward level 9, with level 3 being the minimum we would need (I believe) for constant types.

I am going to use this issue as a list of things we need to update to achieve level 3. The one question we have to answer, is what we do with the `app` directory. Because of views, PHPStan complains about undefined properties (see: `app/Views/base.php`). I'd love to have a permanent solution for this in the long run so that PHPStan doesn't complain about that.

**Comment by brendt** [comment]
Doesn't PHPStan take `@mixin` into account?
