### ISSUE TITLE
Console configuration

### ISSUE THREAD

**Issue by brendt** [tempestphp/tempest-framework#19]
Right now, console commands are mapped straight unto a console class method.

```php
./tempest hello:world input --flag --named=value
```

```php
class Hello implements ConsoleCommand
{
    public function world(string $input, bool $flag = false, ?string $named = null): void
    {
        // …
    }
}
```

This is fine for simple commands, but there are numerous cases where you need more fine-grained control. I imagine it to look something like this, but tbd:

```php
class Hello implements ConsoleCommand
{
    public function world(
        #[ConsoleArgument(
            alias: ['--input', '-i'],
            description: "The path to the input file",
        )]
        string $input,

        #[ConsoleArgument(
            alias: ['-f'],
            description: "Toggle a flag",
        )]
        bool $flag = false,
        
        ?string $named = null
    ): void {
        // …
    }
}
```

**Comment by brendt** [comment]
There already is a `#[ConsoleCommand]` attribute now, a good first step, but more work to be done.

**Comment by aidan-casey** [comment]
@brendt have you thought at all how to handle positional arguments vs. options?

**Comment by brendt** [comment]
I actually want to keep it as close as possible to how named arguments work in PHP. I realise that this way we only cover a subset of how console arguments and options usually work, but since we're auto mapping to method arguments, I don't think it makes sense to make a difference. 

I think of console commands as a way for people to reach a PHP method via text (the console).
