### ISSUE TITLE
Convert Request::$body to a string

### ISSUE THREAD

**Issue by brendt** [tempestphp/tempest-framework#191]
See https://github.com/tempestphp/tempest-framework/pull/157#discussion_r1510166088

**Comment by aidan-casey** [comment]
@brendt - Let's take care of this in #196.

**Comment by brendt** [comment]
Yeah 💪

**Comment by brendt** [comment]
Update: we'll keep body as an array (might rename it to $data if that's preferred). `body` now is the equivalent to `parsedBody` from the PSR request. I'll improve this further when working on files: #201
