### ISSUE TITLE
Safe Functions

### ISSUE THREAD

**Issue by aidan-casey** [tempestphp/tempest-framework#208]
I have been working through our PHPStan errors and have noticed a common theme: The majority of our errors come from the lack of "safe" functions.

For example, see line [95](https://github.com/tempestphp/tempest-framework/blob/c26e60a4341f6aa0213b8eeb194f35e4e7b6422b/src/View/IsView.php#L95) in the `IsView` trait. We are running `ob_get_clean` which can return `false` or `string` and then ultimately returning it from the `render` method. Since `ob_get_clean` can return `false`, we _could_ run into a potential issue though.

It seems like implementing safe functions that throw an exception instead of returning false is the way to go here.

Now, [this](https://github.com/thecodingmachine/safe) package does exist, but it seems to be _somewhat_ abandoned given the backlog of issues and pull requests. Notably, it does not have the one function mentioned in this issue, `ob_get_clean`.

So it seems like we have a few options here...

1. Don't implement safe functions, but add lots of `if` statements.
2. Custom implement all the safe functions we need.
3. Fork `thecodingmachine/safe` and update it OR use it as a dependency and add in the missing functions we might need.
4. Shelve this for another day. 😛  (Though I will note, this will be a lot harder to clean up as the codebase grows.)

**Comment by brendt** [comment]
Do you have a list of which unsafe functions are currently in use besides `ob_get_clean`?

**Comment by aidan-casey** [comment]
Eh, there seems to be about 100+. I don't have any easy way to compile that, but it includes things like `json_*` etc.

**Comment by brendt** [comment]
I don't think we should worry about these functions. I understand that _technically_ they are unsafe, but I don't feel like trying to solve everything. 

If we ever find that eg. unsafe json functions are too much of a hassle, we can write an OO wrapper around these functions. But I would do it on a case-by-case basis.

**Comment by aidan-casey** [comment]
The problem is not so much the functions themselves being unsafe as how they are being used in the codebase. We are always going to have PHPStan problems if they aren't addressed since we are returning a potentially `false` value on a method with a `string` return type.

**Comment by brendt** [comment]
IMO that's a sign that we're running PHPStan at too high a level :) 

I'm definitely not against static analysis, but we should be careful that we're not chasing anything just so that PHPStan can run at a higher level. The goal is that static analysis helps us, not the other way around.

**Comment by brendt** [comment]
PS, apparantly we can ignore single rules by some kind of identifier: https://phpstan.org/user-guide/ignoring-errors#ignoring-in-configuration-file

I think that's the way to go if we want higher levels, but with a bit of finetuning.

**Comment by brendt** [comment]
PS, I'm not against the idea of adding safe functions entirely (which is why I just opened https://github.com/tempestphp/tempest-framework/issues/212)

But I think it's better to tackle this on a case-by-case basis when it actually benefits us.
