### ISSUE TITLE
ReflectionType::getName shenanigans

### ISSUE THREAD

**Issue by brendt** [tempestphp/tempest-framework#212]
In several places throughout Tempest, we use `$reflectionType->getName()` directly, assuming the type is named type. It could however also be a union or intersection type. In some places we manually check for this, in other places we simply ignore the error.

I suggest we add a small wrapper for ReflectionType in `Tempest\Support\Reflection`, that can handle all egde cases. Ideally, it always returns an array of `NamedType` objects, so that we have a consistent way of working with them.

**Comment by aidan-casey** [comment]
I like this idea, @brendt. I do wonder if it would be worth having its own module namespace we can expand upon though.

I know this isn't the intention for Tempest, but I've rewritten the concept of "descriptors" a dozen times and it would be cool if the attribute stuff and everything existed in a separate module that could eventually be made a separate package.

**Comment by tomchkk** [comment]
I had this a few times recently - I handled it something like this:
```php
private function getResolvedPropertyTypeNames(\ReflectionProperty $property): ?array
    {
        if (! $type = $property->getType()) {
            return null;
        }

        /** @var \ReflectionNamedType|\ReflectionIntersectionType|\ReflectionUnionType $type */
        return array_map(
            fn (\ReflectionNamedType $type) => $type->getName(),
            $type instanceof \ReflectionNamedType ? [$type] : $type->getTypes()
        );
    }
```

**Comment by aidan-casey** [comment]
> If we ever extract anything from Tempest, it would be this kind of code.

My only thought was that _eventually_ we split up all the components to packages with this being the mono-repo (similar to Laravel).

> had this a few times recently - I handled it something like this

Nice! We are basically doing this [here](https://github.com/tempestphp/tempest-framework/blob/main/src/Container/GenericContainer.php) on line 256. We've had to replicate this functionality in enough places that it makes sense to extract out. 🙂

**Comment by brendt** [comment]
Added a super simple helper `type` in tempest/core. This suffices for now
