### ISSUE TITLE
Unable to discover installed packages location when using packages like `roave/security-advisories`

### ISSUE THREAD

**Issue by krzysztof-alboszta** [tempestphp/tempest-framework#219]
`roave/security-advisories` is a package that does not provide any API or usable classes, and therefore it doesn't need to install any files into the project. `'install-path'` property is set to `NULL`

In the `\Tempest\Bootstraps\DiscoveryLocationBootstrap::discoverInstalledPackageLocations` method all packages are retrieved from composer `installed.json` file and for each of them the package path is defined like this:
```php
            $packagePath = path($composerPath, $package['install-path']);
```
this might lead to throwing `TypeError`
> TypeError: Tempest\path(): Argument #2 must be of type string, null given

To avoid that, this Discover method should filter out such packages.

One solution would be to filter out all `dev` packages by checking `dev-package-names` key in the `installed.json` file

**Comment by brendt** [comment]
Thanks for noticing! I've added an extra fallback for now!
