### ISSUE TITLE
Finalize `NullShellExecutor`

### ISSUE THREAD

**Issue by aidan-casey** [tempestphp/tempest-framework#259]
The `NullShellExecutor` is currently tested using mocks. This prevents us from making the class final.

We should revise the tests for that class and finalize the class.

**Comment by Qupiter** [comment]
Hey there, can you assign this issue to me? 
I would like to work with you. This seems like a good issue to start with.

**Comment by alibori** [comment]
Hi @aidan-casey !

This issue can be closed, isn't it? If I'm right the `NullShellExecutor` class is final.

Thank you! 😃

**Comment by aidan-casey** [comment]
Hey, @alibori! It is final, but has no tests. We still need to refactor so we can test it. 🙂

**Comment by brendt** [comment]
No no, I fixed that, just forgot to close the issue
