### ISSUE TITLE
Environment isStaging method is not present

### ISSUE THREAD

**Issue by bYemma** [tempestphp/tempest-framework#263]
The method `isStaging()`  is not defined in Environment enum.

https://github.com/tempestphp/tempest-framework/blob/a3cec1ef41631774b052624d8df72ebc70e8c71d/src/Tempest/Console/Middleware/CautionMiddleware.php#L25

Should this call be removed in the middleware? Or should the method be added to the enum?

**Comment by brendt** [comment]
It looks to be there, I think: https://github.com/tempestphp/tempest-framework/blob/main/src/Tempest/Framework/Application/Environment.php#L21

**Comment by bYemma** [comment]
I didn't find it here on GitHub. I don't know, why. Maybe I was in some branch or so.
Sorry, my mistake!

**Comment by brendt** [comment]
No problem, thanks for checking!
