### ISSUE TITLE
Filesystem

### ISSUE THREAD

**Issue by brendt** [tempestphp/tempest-framework#272]
Needed for 

- tempestphp/tempest-framework#123 
- tempestphp/tempest-framework#201

**Comment by brendt** [comment]
Do we really need this before 1.0?

**Comment by shaffe-fr** [comment]
I think Tempest needs file upload management for 1.0. It's pretty tedious with vanilla PHP. 
I guess local driver is required for that. Multiple disks support is bonus but should not be so tough once it's done. 
Are you considering wrapping flysystem?

**Comment by aidan-casey** [comment]
@shaffe-fr I'm _thinking_ we should separate out local filesystem and third-party storage as two different packages in Tempest world, with priority on the former.

**Comment by shaffe-fr** [comment]
I like your idea to use Filesystem for framework level stuff and Storage for application level. 👌
We could start with Filesystem and Storage with local driver only. That would not require to hook on Flysystem.

**Comment by brendt** [comment]
I really like the difference between fs and storage as well 👍👍
