### ISSUE TITLE
Discovery on Windows doesn't work

### ISSUE THREAD

**Issue by brendt** [tempestphp/tempest-framework#273]
https://github.com/tempestphp/tempest-app/actions/runs/9203485022/job/25315100490

My guess is that it has to do with reading files, a `glob` or `is_file` or `file_exists` function somewhere within the bootstrappers is the most likely culprit. Maybe something with filesystem permissions?

**Comment by kickofitall** [comment]
I stumbled upon the error myself and was able to narrow it down to the following line in [DiscoveryBootstrap.php](https://github.com/tempestphp/tempest-framework/blob/b4393ab89f13ad66b8607789b41babbfe88f1313/src/Tempest/Framework/Bootstraps/DiscoveryBootstrap.php#L41):

**not working**
`$directories = new RecursiveDirectoryIterator($discoveryLocation->path);`

**working**
`$directories = new RecursiveDirectoryIterator($discoveryLocation->path, RecursiveDirectoryIterator::UNIX_PATHS);`

Later in the code, `$discoveryLocation->path` ends with a "/".
`$file->getPathname()` uses "\\" from the same position until the end of the string.
This means that `str_replace` cannot replace the path [here](https://github.com/tempestphp/tempest-framework/blob/b4393ab89f13ad66b8607789b41babbfe88f1313/src/Tempest/Framework/Bootstraps/DiscoveryBootstrap.php#L59).

---

Just to mention, there is another flag `RecursiveDirectoryIterator::SKIP_DOTS.`
Maybe that would allow you to [omit the check in line 48](https://github.com/tempestphp/tempest-framework/blob/b4393ab89f13ad66b8607789b41babbfe88f1313/src/Tempest/Framework/Bootstraps/DiscoveryBootstrap.php#L48).

**Comment by brendt** [comment]
Ah, awesome! Thanks for looking into this. Do you wanna submit a PR? I can do it, but if you'd like the contribution, I'm happy to merge it :) Let me know!

**Comment by kickofitall** [comment]
Sure, I'd like to contribute.

There is another small code fragment that doesn't work under Windows.
I'd also include that in the PR.

**Comment by brendt** [comment]
Ah, cool! I actually just pushed a WIP commit to main to test out the things you were talking about :D https://github.com/tempestphp/tempest-framework/commit/e08549753aecd634a156b540ab938d77346ede23

Feel free to try it out, send a PR if anything pops up :)

**Comment by kickofitall** [comment]
Great! I'll take a look at it.

**Comment by brendt** [comment]
This seems to be fixed now with #333
