### ISSUE TITLE
`:uri` attribute

### ISSUE THREAD

**Issue by brendt** [tempestphp/tempest-framework#278]
a `:uri` attribute can automatically be transformed to `href="real URI"`

```
<a :uri="HomeController::class"></a>
<a href="/"></a>
```

**Comment by Treggats** [comment]
Should every method in the `TestController::class` be covered?

**Comment by brendt** [comment]
No you don't need to test all these methods. However, I just realised: how should we pass in route parameters? 🤔 Maybe this feature won't work at all 😅

**Comment by Treggats** [comment]
> No you don't need to test all these methods. However, I just realised: how should we pass in route parameters? 🤔 Maybe this feature won't work at all 😅

I was doing some fancy things with thee container to resolve the controller. Maybe too fancy at this stage.

**Comment by brendt** [comment]
Yeah let's just close this one for now :) Thanks for looking into it though!
