### ISSUE TITLE
Migration SQL dialect

### ISSUE THREAD

**Issue by brendt** [tempestphp/tempest-framework#291]
The `CreateMigrationsTable` class is written for SQLite, which isn't compatible with MySQL. Maybe we should provide three different implementations (SQLite, MySQL and postgres), the developer will need to publish the right migration file when setting up the database.

**Comment by brendt** [comment]
Well we started off with something like `Blueprint`, but eventually decided against it: https://github.com/tempestphp/tempest-framework/issues/80

The problem right now is that there's only one implementation for `CreateMigrationsTable`, written for SQLite. On top of that, this migration gets automatically discovered by Tempest, which means that running migrations on anything else but SQLite won't work (incompatible syntax). 

My idea was to have three files, one my MySQL, SQLite, and postgres. These files shouldn't be discovered automatically. I think it's as easy as renaming them to `CreateMigrationsTableMysql.php.stub`.

Whenever we run `migrate:up` for the first time, we can check whether there's already a `CreateMigrationsTable` migration loaded. If not, we can prompt the user and ask if it's ok to create one. This would copy of of the stubs to the project — depending on the configured driver.

It's a bit of a complex feature that touches many areas of the framework. Let me know if you're up for it, and I'm happy to help!

**Comment by Treggats** [comment]
Reading your comment I formed the same idea in my mind before I read you saying it 😅 

Yeah I'm up for it sounds like a fun challenge.

**Comment by brendt** [comment]
Awesome! Ping me on Discord if you have any questions :)
