### ISSUE TITLE
[bug] sorting migrations are not done by name

### ISSUE THREAD

**Issue by Treggats** [tempestphp/tempest-framework#297]
**Problem**
It seems that the order in which migrations are run, are either not working as expected or I haven't got migration naming correct.

**Scenario**
When running two migrations, where the latter creates a constraint on the former.
The one with the constraint is run before the referenced table is created.

Running the two migrations separate is a work around in this case.

**Steps to reproduce**
- Create two migrations with the following statements
- run `php tempest migrate:up`
- the following error occurs
    `General error: 1824 Failed to open the referenced table 'authors`

<details>
<summary>Tabel 1 (authors)</summary>

```sql
# migration name: 1970-01-02_create_authors_table
create table if not exists authors (
    id bigint auto_increment primary key,
    name varchar(255) not null
);
```

</details>

<details>
<summary>Table 2 (books)</summary>

```sql
# migration name: 1970-01-03_create_books_table
create table books
(
    id        bigint auto_increment primary key,
    title     varchar(255) not null,
    author_id bigint       null,
    constraint books_authors_id_fk foreign key (author_id) references authors (id)
);

create index books__authors__index on books (author_id);
```

</details>

**Comment by brendt** [comment]
Yeah they should definitely be sorted. Do you wanna take a look? I'm happy to fix it as well

**Comment by Treggats** [comment]
I'm working in there already, so it can help me understand the inner working more. So I'll take a look.
If you have any pointers that might help I'm all ears :)
