### ISSUE TITLE
[feature] add support for multiple database engines

### ISSUE THREAD

**Issue by Treggats** [tempestphp/tempest-framework#298]
resolves #179 #291

fixes #297

**Situation**
At the moment the initial migration is SQLite only. In order to support multiple database engines we need a way to load migrations with their own SQL dialect.

**Proposed changes**
Combine the above mentioned issues.

- [ ] create SQL files with the migration table creation, for every database driver we currently support
- [ ] the name of the migration should dictate the order that they are run in 
        (#297)
- [ ] let the `CreateMigrationTable` class decide which file to use, based on the currently configured database driver
- [ ] let user generated migrations use the same approach

**Comment by brendt** [comment]
Some pointers to help you along:

Migration files are automatically discovered via `\Tempest\Database\MigrationDiscovery`. This discovery class will find migration files, and will register them in `\Tempest\Database\DatabaseConfig`. 

As you can see in that config class, there's no sorting being done yet.

On top of that, if we want to support raw SQL files, I think we need some kind of `RawMigration` class that holds a dynamic query. `MigrationDiscovery` will need to be able to detect these raw files. I imagine it looking something like this:

```php
// MigrationDiscovery


    public function discover(ReflectionClass|string $class): void
    {
        if (is_string($class)) {
            $this->discoverPath($class);

            return;
        }
        
        if (! $class->isInstantiable()) {
            return;
        }

        if (! $class->implementsInterface(Migration::class)) {
            return;
        }

        $this->databaseConfig->addMigration($class->getName());
    }

    private function discoverPath(string $path): void
    {
        if (! str_ends_with($path, '.sql')) {
            return;
        }

        if (! is_file($path)) {
            return;
        }

        $this->databaseConfig->addMigration(new RawMigration(
            name: 'tbd',
            path: file_get_contents($path),
        ));
    }
```

It's actually an undocumented feature that discovery classes can also accept strings. This is something I need to improve in the future. You can see the same thing happening in `\Tempest\View\ViewComponentDiscovery`, which also supports discovery of view files and not just PHP classes.
