### ISSUE TITLE
Kernel refactor

### ISSUE THREAD

**Issue by brendt** [tempestphp/tempest-framework#311]
Moving bootstraps to application level and cleaning things up, including config discovery

**Comment by aidan-casey** [comment]
Here is a diagram of how we will try and set this up. The goal will be to eliminate the chicken and egg problem with the bootstrappers where they are discovering config files, but need the app config to work.

![image](https://github.com/user-attachments/assets/d3cbe21e-7563-4dd2-a83e-9dbb57060eb3)

---

@brendt - One thing we've talked about in the past is decoupling discovery from the Tempest container. A specific example I can think of where that might be useful is a minimal console application, a non-Tempest application using the command/event bus, etc. To confirm, you are _not_ wanting to do that?

**Comment by brendt** [comment]
> To confirm, you are not wanting to do that?

I confirm, I do not want to do that :p

**Comment by brendt** [comment]
Related: #365 , #366

**Comment by brendt** [comment]
I'd say it's good enough for now.
