### ISSUE TITLE
migration info is shown twice on the console

### ISSUE THREAD

**Issue by Treggats** [tempestphp/tempest-framework#316]
Not really a bug, more like user experience.

**Description**
When running `php tempest migration:down` on an empty database it shows the following message on the console

```plain
~/P/tempest-app ❯❯❯ php tempest migrate:down
 Error while executing migration: Migration 
 Migrations table does not exist. Nothing to roll back. 
 Error while executing migration: Migration 
 Migrations table does not exist. Nothing to roll back. 
 Done 
Rolled back 0 migrations
```

So the same messages twice.

**Initial test to reproduce**
Note; some of the methods used here aren't in the current codebase.
```php
public function test_errors_when_no_migrations_to_rollback(): void
{
    $this->console
        ->call('migrate:down')
        ->assertCountText(1, MigrationException::noTable()->getMessage());
}
```

**Comment by brendt** [comment]
Fixed it. The problem here was that both the `MigrateUp` and `MigrateDown` command registered listeners for the same `MigrationFailed` event. I moved that listener to a dedicated class instead.
