### ISSUE TITLE
Rename `Model` to `DatabaseModel`, as well as `IsModel` to `IsDatabaseModel`

### ISSUE THREAD

**Issue by brendt** [tempestphp/tempest-framework#330]

**Comment by Treggats** [comment]
Maybe it's me, but what's the reasoning behind the name `IsModel`?

**Comment by brendt** [comment]
It's a naming convention we came up with to distinguish between the interface and the trait. For now we're stuck with it. I hope PHP one day will get either interface default methods or be able to typehint on traits, or allow traits to implement interfaces.

**Comment by Treggats** [comment]
> I hope PHP one day will get either interface default methods or be able to typehint on traits, or allow traits to implement interfaces.

That's the dream :)

Reason of me asking is that that wasn't clear to me, the difference so to speak.

I've seen that within Laravel there's `Contract` for interfaces and `Concerns` for traits, which make sense to me.
And back when I was working on a Java application, it had `Interface` for interface. Which is pretty literal 😅.  I can't remember if Java has traits or not, so don't know if there is a convention on that.
