### ISSUE TITLE
Make configs discoverable

### ISSUE THREAD

**Issue by brendt** [tempestphp/tempest-framework#362]
We'll need to decide on how to do that, and then provide a `ConfigDiscovery`

**Comment by nuernbergerA** [comment]
maybe something like this

```php
class MyDatabaseConfig implements UserConfig
{
    public function configure(): Config
    {
        return new DatabaseConfig(
            connection: new SQLiteConnection(
                path: __DIR__ . '/../database.sqlite',
            ),
        );
    }
}
```

**Comment by brendt** [comment]
Gotcha!

**Comment by brendt** [comment]
Another idea I brainstormed was to keep the config as-is, and have the discovery class require all paths, in an attempt to discover which config files are returning a config object. But that's kind of a mess

**Comment by nuernbergerA** [comment]
or maybe something like this, that registers itself?
```php
config()->replace(new DatabaseConfig(
    connection: new SQLiteConnection(
        path: __DIR__ . '/../database.sqlite',
    ),
));
```

**Comment by nuernbergerA** [comment]
Or maybe leverage `composer.json` [extra](https://getcomposer.org/doc/04-schema.md#extra) 

usage example: https://github.com/spatie/laravel-route-attributes/blob/c320d0c59730ec57c7e977c35d48781e8a2e4d84/composer.json#L46

**Comment by aidan-casey** [comment]
@brendt for what it's worth (which isn't much), I've done a ton of thinking on this and there's not a 100% great solution. The best I could come up with was:

1. Tempest default is to look for `config` in the root project directory matching the standards set by Symfony and Laravel.

2. Use a service class (not a bootstrap) to load these configuration files and have it perform the locating with locator classes/drivers. This way if someone really wants to go through the hassle of changing the directory or we decide it makes sense to change the approach down the road, we can easily.

**Comment by brendt** [comment]
Fair enough, but if that's the best option, then we might as well keep it as is for now…

**Comment by brendt** [comment]
> Or maybe leverage composer.json [extra](https://getcomposer.org/doc/04-schema.md#extra)

I considered this briefly as well, but it would mean people should make changes to their composer.json every time they add a config file. That sucks

**Comment by brendt** [comment]
I slept a night on the problem. Everything sucks one way or another, so I see no benefit in changing it. The current solution is the least writing for the end user. We might consider adding some kind of `ConfigProvider`/`UserConfig` interface in the future as @nuernbergerA proposed, but for now it's good enough.
