### ISSUE TITLE
Map Upload files into request properties

### ISSUE THREAD

**Issue by brendt** [tempestphp/tempest-framework#370]
```php
class MyRequest implements Request
{
    use IsRequest;
    
    public Upload $avatar;
}
```

**Comment by brendt** [comment]
Are you sure this works? Because `$from->getFiles()` is an array without named keys?

**Comment by yassiNebeL** [comment]
Yes, we need a named keys, any idea how we can resolve that? when I tried to map the request to a model object with `ArrayToObjectMapper` because we couldn't find the property name with the array keys.

**Comment by yassiNebeL** [comment]
We need to add the `uploadedFiles` as well, now `getFiles` returns an array with named keys.

```php

final readonly class RequestToPsrRequestMapper implements Mapper
{
   ...

    public function map(mixed $from, mixed $to): PsrRequest
    {
        /** @var Request $from */

        return new ServerRequest(
            uri: $from->getUri(),
            method: $from->getMethod()->value,
            headers: $from->getHeaders(),
            cookieParams: $from->getCookies(),
            queryParams: $from->getQuery(),
            parsedBody: $from->getBody(),
            uploadedFiles: $from->getUploadedFiles()
        );
    }
}
```

Continuing with the Book example after adding `coverPicture` property the request along with the Book model this is what I got:

```
INSERT INTO `Book` (title, coverPicture) VALUES (:title, :coverPicture);

bindings: {
    "title": "tittre 1",
    "coverPicture": null
}
```

Could you tell me which value should I store in the DB?

**Comment by brendt** [comment]
I think the easiest path forward is to submit a PR that I can review ;)

**Comment by yassiNebeL** [comment]
@brendt, the mapping between `PsrRequest` and `Request` works properly. I believe the mapping between `Request` and `Model` is also correct, but I encountered an error when trying to save the `Book` model using #702.

The error message is: "Object of class Tempest\Http\Upload could not be converted to string."

We can easily implement the `__toString` method in the Upload class to return the path. let me know if I need to create a new issue regarding the issue encountered.

What do you think about it?

**Comment by yassiNebeL** [comment]
@innocenzi Thank you for you reply, I understand that @brendt  doesn't work full-time in Tempest.   

My intention was not to rush or an immediate action but to express that Ive been disconnected from the project despite my efforts. I just want to clarify my position and the frustration that comes with contributing without feedback.

I appreciate the work done, and I'm still open to contributing if things change.
