### ISSUE TITLE
Auto detect vendor packages

### ISSUE THREAD

**Issue by brendt** [tempestphp/tempest-framework#38]
Right now, you need to manually add packages to `AppConfig::packages` which is annoying. Let's write a discovery class to detect packages in vendor files. 

This will be a special kind of discovery though, since it'll have to run on the vendor folder, and it'll have the change the packages array in `AppConfig`, _before_ all other discoveries are run. We might need to consider refactoring `Kernel::initDiscover` a bit if there's too much code duplication. At first though, I'd simply add a `Kernel::initPackages` similar to `Kernel::initConfig`. It'll have to run as the first step after the container has been created, because both `initConfig` and `initDiscovery` depends on the full list of packages.

**Comment by brendt** [comment]
@aidan-casey we need some way to mark a vendor directory as a Tempest Package, I don't think it makes sense to scan _all_ vendor directories. 

One idea I came up with is to have a class that relies on a naming convention: it should live in the root of your package's `src` folder, and be suffixed `Package`. It kind of sucks.

Maybe we can read `composer.json` for some kind of meta data key, but that would require us parsing composer JSON files, I don't really like that either…

**Comment by aidan-casey** [comment]
@brendt - Why are you hesitant to scan everything in vendor?

Keep in mind, for performance reasons, we don't want to scan all the directories, we just want to scan all the classes registered in the classmap.

**Comment by aidan-casey** [comment]
@brendt - See [here](https://github.com/aidan-casey/tempest-framework/tree/adds-vendor-benchmark) for a super rough benchmark. It's not even trying to be performant, but makes it through pretty quick. I added laravel/framework as a dependency just to have a good chunk of files to work through.

**Comment by aidan-casey** [comment]
@brendt - So I just realized the composer classmap would actually include anything in your app directory anyway. Do you see a scenario where you support using Tempest _without_ composer? Otherwise it might make sense just to use composer's classmap for loading across the board.

**Comment by brendt** [comment]
> Do you see a scenario where you support using Tempest without composer

No, composer is required. I vaguely remember trying to use composer's classmap before, but I ran into some issues with it. I can't remember what. I'll look into it once again, since I think it would be best if composer could do the heavy lifting for us 👍

**Comment by aidan-casey** [comment]
@brendt - I worked on a rough draft of this yesterday. The issue with iterating over every class and creating a reflection class is that some of them (looking at you Symfony!) reference constants that are loaded using the Amqp extension and throw a fatal error. Since you cannot ignore fatal errors without some serious hacking that becomes a problem.

For kicks, I ran a string comparison with the file contents and checked for a Tempest attribute (InitializedBy) by its full namespace name prior to creating the reflection class with almost no negligible difference. Doesn't feel as clean and buttoned up, but it did work.

**Comment by brendt** [comment]
I'll be working on it some more today, on stream as well :) we can continue to finetune afterwards :)

**Comment by brendt** [comment]
We're now including packages that have a dependency on `tempest/framework` 👍

**Comment by aidan-casey** [comment]
@brendt - now that this is closed... I had a thought. 😅

A script could get setup to cache this after a composer install/update command so it happens when the package is added, not when Tempest is run (let composer take the performance hit).

**Comment by brendt** [comment]
Yes, great idea! https://github.com/tempestphp/tempest-framework/issues/59
