### ISSUE TITLE
Response Objects

### ISSUE THREAD

**Issue by aidan-casey** [tempestphp/tempest-framework#39]
@brendt - ASP.NET has some helper responses that allow for the easy generation of API responses. Any reason we could not add some support for a similar concept in object form? Those could in turn be used for some response helpers such as `Ok`.

_Examples_

```php
final readonly class CreatePetController
{
    #[Post(uri: '/api/v1/pets')]
    public function __invoke(CreatePetRequest $request): Created
    {
        $pet = map($request)->to(Pet::class)->save();

        return new Created($pet);
    }
}

final readonly class CreateOwnerController
{
    #[Post(uri: '/api/v1/owners')]
    public function __invoke(CreateOwnerController $request): Created
    {
        $pet = map($request)->to(Owner::class)->save();

        return new Created(
            value: $owner,
            uri: uri(ShowOwnerController::class, $owner) // Sets the Location header
        );
    }
}
```

_References_

- https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.controllerbase.created?view=aspnetcore-8.0
- https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.controllerbase.ok?view=aspnetcore-8.0
- https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.controllerbase.createdataction?view=aspnetcore-8.0

**Comment by brendt** [comment]
Looks good! Are you up for sending a PR? :)

**Comment by aidan-casey** [comment]
Absolutely! Just wanted to float the idea before putting in the work. 🙂

**Comment by alibori** [comment]
Hi both!

Which helper responses are you thinking about? I would like to help at this point (or at least try to 😜 ). My approach would be base on this [article](https://juststeveking.uk/articles/laravel-response-classes/)

What do you think?

Thanks!

**Comment by aidan-casey** [comment]
Hey @alibori! Essentially these objects should be classes that use `BaseResponse` and implement best practices for that response type.

For example, in the case of a created response, it might look something like this:

```php
namespace Tempest\Http\Response;

final class Created
{
    use BaseResponse;

    public function __construct(object $value, string $location)
    {
        parent::__construct(Status::CREATED, json_encode($value), ['Location' => $location]);
    }
}
```

Please note that is a super rough example!

The one thing we might want to explore, but instantly makes this more complex is serializers for the response to match what the header requests.

**Comment by alibori** [comment]
Hey @aidan-casey !

Ok, I'll take a look and try to achieve it.

Thanks!

**Comment by aidan-casey** [comment]
Thanks @alibori! Feel free to ping me if I can offer any assistance here!

**Comment by alibori** [comment]
Hi @aidan-casey !

I'm starting to work on it and, as you told me 😜 , I ask for your assistance about how to implement it. Here I go:

- In `src\Http` I'd created a `Responses` folder. For now I create a `CreatedResponse` into it. For now, it looks like:

```php
<?php

declare(strict_types=1);

namespace Tempest\Http\Responses;

use Tempest\Http\IsResponse;
use Tempest\Http\Response;
use Tempest\Http\Status;

final class CreatedResponse implements Response
{
    use IsResponse;
    
    public function __construct(
        private mixed $body,
        private array $headers = []
    )
    {
        $this->status = Status::CREATED;
        $this->body = json_encode($body);
    }
}
```

Is this something similar to what you have in mind?

Then, in addition, we can create a response helper too like Laravel does if necessary/interesting.

Please, tell me your thoughts about 😊 

Thanks!

**Comment by aidan-casey** [comment]
Hey, @alibori! I apologize for my delayed response. I have not forgotten about your message, but I do think there are a couple things that might effect this in the near future (e.g., #128).

That is indeed what I had in mind though! The one thing I'm trying to think on is whether we could support various serialization forms (json, xml, etc.) based off the accept header.

**Comment by brendt** [comment]
I've looked at those changes, tl;dr: all responses now support a body being a string or an array: `private string|array $body = '',`

Apart from this, there should be no difference in implementing these request classes.

@aidan-casey did you have a list in mind of which classes we want to add?

**Comment by aidan-casey** [comment]
@brendt - why are we supporting arrays at all in a response body? Shouldn't a response encapsulate the plain text that is being sent back to the client, while any serialization or formatting happens prior to the building of that response?

I do. I can assemble that list and add it to the issue.

**Comment by brendt** [comment]
> why are we supporting arrays at all in a response body

Because it's one of the most common data structures that are sent to clients apart from HTML. It happens to be encoded in JSON, but essentially we want to send arrays/JS-like objects over the wire. Whether it should be a string is an implementation detail of the HTTP protocol that Tempest users shouldn't be concerned about.

**Comment by alibori** [comment]
Hi @brendt and @aidan-casey !

I've been disappeared for a while due to work load, sorry.

Let you know that I'm aware of this issue to work on it when Aidan can define the desired list ☺️ . I suppose that this won't be soon because it's not included in the next milestone, right?

I'll try to contribute with other issues meanwhile!

Thank you!

**Comment by WendellAdriel** [comment]
@alibori is there anything I could help with on this?

**Comment by alibori** [comment]
@WendellAdriel Thank you for your comment 😊 

Well, as far as I know @aidan-casey will write a list of the desired response classes. Any case, it would be great to collaborate with you.

Kind regards!

**Comment by WendellAdriel** [comment]
Nice, thanks @alibori!

When that's defined I can help you with the implementation if you want! 💪

**Comment by brendt** [comment]
#246
