### ISSUE TITLE
[Bug]: Console suggestions are repeated once per alias

### ISSUE THREAD

**Issue by brendt** [tempestphp/tempest-framework#411]
### Tempest Version

1.0-alpha1

### PHP Version

8.3

### Operating System

MacOS

### Description

```
[ ] discovery:cache
[ ] discovery:cache
[x] discovery:status
[ ] discovery:status
[ ] discovery:clear
[ ] discovery:clear
```

### Steps to Reproduce

/

**Comment by Treggats** [comment]
@brendt can you assign me? I've been wanting to look into this part of Tempest.

Also, the steps to reproduce are rather empty

**Comment by brendt** [comment]
My bad 😇

```
./tempest di
```

shows the issue

**Comment by Bapawe** [comment]
Hey @Treggats , I noticed this issue was assigned to you, but I’ve already started working on a fix in my branch:

https://github.com/tempestphp/tempest-framework/compare/main...Bapawe:tempest-framework:fix-resolve-or-rescue-middleware

I’ve added a `ResolveOrRescueMiddlewareTest` to reproduce the bug and applied the fix in the middleware itself. Currently, I’m using the discovery commands for testing, although I realize this might not be the best approach.

**Comment by Treggats** [comment]
hey @Bapawe, yeah. It's best if you want to work on something you ask to get assigned, so we don't end up working on the same :)

> Currently, I’m using the discovery commands for testing
I'm not sure what you mean by this.

Regarding the changes, I also started with a test. Was still looking where the list got generated. Would you be okay if I incorporate your changes into my work?

**Comment by Bapawe** [comment]
> hey @Bapawe, yeah. It's best if you want to work on something you ask to get assigned, so we don't end up working on the same :)

Yeah i thought so, that's why i created the comment 😉 

> > Currently, I’m using the discovery commands for testing
> > I'm not sure what you mean by this.

I mean, it works but it might be better to use a new test command fixture specifically for the ResolveOrRescueMiddlewareTest. 

> Regarding the changes, I also started with a test. Was still looking where the list got generated. Would you be okay if I incorporate your changes into my work?

Sure, go ahead!

**Comment by Treggats** [comment]
> I mean, it works but it might be better to use a new test command fixture specifically for the ResolveOrRescueMiddlewareTest.

A fixture is a good idea, hadn't looked into that yet.
