### ISSUE TITLE
GitHub CI Actions for testing project creation

### ISSUE THREAD

**Issue by brendt** [tempestphp/tempest-framework#42]
- [x] An action that runs `composer create-project tempest/app` and makes sure that `./tempest` works, then runs the built in `./tempest serve` server to make sure the webapp works as well
- [x] An action that runs `composer require tempest/framework` in an empty project and makes sure that `vendor/bin/tempest install` works, then runs the built in `./tempest serve` server to make sure the webapp works as well

**Comment by aidan-casey** [comment]
@brendt - Can I suggest this just gets added as an action the individual repos? Running `composer` commands doesn't necessarily help isolate version-specific problems and requires publishing to packagist. Ideally we are catching these issues _before_ that point.

**Comment by brendt** [comment]
Makes sense, I just created this issue here so that I wouldn't forget; we can flesh out the details once someone starts working on it.

**Comment by brendt** [comment]
`tempest/app` now works:

- https://github.com/tempestphp/tempest-framework/blob/main/.github/workflows/trigger-tempest-app-qa.yml
- https://github.com/tempestphp/tempest-app/actions/runs/8111342491

**Comment by brendt** [comment]
A clean tempest install now also works:

- https://github.com/tempestphp/tempest-framework/blob/main/.github/workflows/trigger-tempest-clean-qa.yml
- https://github.com/tempestphp/tempest-app/actions/runs/8111734557
