### ISSUE TITLE
ViewComponent attribute bugs

### ISSUE THREAD

**Issue by brendt** [tempestphp/tempest-framework#450]
## Passing a variable previously defined doesn't work ✅

```php
<?php
$meta = MetaType::CONSOLE;
?>

<x-base title="Console" :meta="$meta">
```

## attribute name casing problem ✅ (kind of fixed)

```php
<x-base title="Console" :metaType="abc">

// $metaType now known in parent
```

## Attributes passed to parent are only accessible via $this ✅

```php
<?php $meta ?> // doesn't work
<?php $this->meta ?> // works

```

## `<x-slot></x-slot>` does not work✅

Only `<x-slot />` does

**Comment by yassiNebeL** [comment]
Hey @brendt, while I was working in the upload stuff, I saw that attributes aren't passed to the component so, I reported it in #381.

Could you take a look because I updated the #381, and let know if I need to close it!

**Comment by brendt** [comment]
Should be fixed once this is merged :)

**Comment by brendt** [comment]
I made an issue about the casing conventions, we need to document them: 458
