### ISSUE TITLE
[Feature Request]: Clarify docs for "The Commandbus"

### ISSUE THREAD

**Issue by Wulfheart** [tempestphp/tempest-framework#481]
### Description

Some uncertainties I had when reading the docs:
1. In the example below I thought at first that `onCreateUser` is required for discovery.
```php
final class UserHandlers
{
    #[CommandHandler]
    public function onCreateUser(CreateUser $createUser): void
    {
        User::create(
            name: $createUser->name,
            email: $createUser->email,
            password: $createUser->passwordHash,
        );
        
        // Send mail…
    }
}
```

2. Is there another method to dispatch commands than the `command()` function?
3. Sometimes I have queries which I also want to dispatch. Can I also return things from the command and just call it query?

### Benefits

Just my thoughts as a newcomer. I am really excited for this framework.

**Comment by aidan-casey** [comment]
Hey, @Wulfheart!

1. I'd be open to hearing how we could phrase this better. Just for reference, this is what is in the docs:

> Just like controller actions and console commands, command handlers are discovered automatically: every method tagged with #[CommandHandler] will be registered as one. The command this method accepts is determined by the parameter type.

2. Yes. Just type hint `Tempest\CommandBus\CommandBus` in your constructor and call `$commandBus->dispatch(...);`.

3. No. Command handlers specifically have a `void` return type. I believe the goal would be to add a query bus in the future.

**Comment by brendt** [comment]
Good questions though, I'll address them in the docs as well

About the query bus: yeah that would need to be something different (the return type is different, but the middleware interface would be different as well). 

It's not planned right now, but @aidan-casey does want to look into improved queuing and an improved event bus after v1.0, we can consider a query bus then as well.

**Comment by Wulfheart** [comment]
> 1. I'd be open to hearing how we could phrase this better. Just for reference, this is what is in the docs:

I would just change the method name to handle or something and add a comment that the method name doesn’t matter. Then it would be obviously on a glimpse. 



> About the query bus: yeah that would need to be something different (the return type is different, but the middleware interface would be different as well).

Without knowing the intricacies of this bus I know that the League Tactician Bus supports this by just returning the value. I think this is a good approach but I am not that deep in the matter.

**Comment by brendt** [comment]
You _could_ in theory merge the two concepts together, they are similar from a technical point of view. However, they are very different from a conceptual point of view. That's why — in my mind — I like to keep these concepts apart. It's a subjective preference, but I feel like it has served me well in the past. 

Ross Tuck, who helped write Tactician once wrote a very interesting article on the topic of returning from command busses: https://www.rosstuck.com/returning-from-command-buses

**Comment by brendt** [comment]
Updated the docs :)
