### ISSUE TITLE
Loading an empty relation

### ISSUE THREAD

**Issue by brendt** [tempestphp/tempest-framework#495]
### Tempest Version

1.0-alpha1

### PHP Version

8.3

### Operating System

MacOS

### Description

Loading a relation without any entries will result in `null` for the parent model

### Steps to Reproduce

A:hasMany(B)

A::query->with('B') // without any entires

A will be null (because of inner join)

**Comment by brendt** [comment]
Fixed with #493

**Comment by blackshadev** [comment]
@brendt #493 is merged so can this be closed?
