### ISSUE TITLE
[Suggestion] Different approach to HTTP middlewares

### ISSUE THREAD

**Issue by MateusAzevedo** [tempestphp/tempest-framework#496]
Hey folks!

I was reading Tempest documentation about [middlewares](https://tempestphp.com/docs/framework/03-controllers/#content-middleware) and it immediately reminded me of a [blog post](https://blog.ircmaxell.com/2016/05/all-about-middleware.html) by Anthony Ferrara!

Knowing that you @brendt like strict types and static analysis, an approach as described there could be a great addition to Tempest.

Not necessarily a feature request, but just a suggestion, food for thought.

**Comment by brendt** [comment]
My guess is you're talking about the Frame part?

**Comment by MateusAzevedo** [comment]
Yes! Sorry I wasn't clear.

But now that you asked, I realized it doesn't make that much sense as we don't have a PSR interface like that we need to follow and need to be abstracted from.

It still has one benefit though, no need to docblock `$response` return type.

**Comment by brendt** [comment]
So, unfortunately PhpStorm has a bug where it doesn't take into account the interface's docblock (https://youtrack.jetbrains.com/issue/WI-79249/Resolving-type-info-from-interfaces-docblock)

I'm still undecided whether I want to provide a `Frame` class, or just wait until PhpStorm fixes the problem.

I've already added the docblocks on the interface in the meantime: https://github.com/tempestphp/tempest-framework/pull/515

**Comment by aidan-casey** [comment]
@brendt - Do we know anyone who works for PhpStorm and can push this along? 🙃

**Comment by innocenzi** [comment]
I might be the outlier here, but I use Code as my main IDE (yes, even for PHP) for a lot of reasons, and its type support is... not great. Which is why I would love the `Frame` implementation instead.

**Comment by brendt** [comment]
That's a fair point. I'm hesitant because I'd want to update all middleware interfaces (there are four: http, console, command, and event). But I agree that it'll be better. I'll add it to my todo :) 

Sidenote: @innocenzi you should try out PhpStorm ;) 😂 but I might be biased
