### ISSUE TITLE
[Bug]: Failed form requests redirecting to same Uri but with Get method

### ISSUE THREAD

**Issue by NeoIsRecursive** [tempestphp/tempest-framework#506]
### Tempest Version

1.0-alpha1

### PHP Version

8.3

### Operating System

MacOS

### Description

(sorry if this is a duplicate, or already fixed, couldn't find anything about this)

Lets say you have three routes
- Get /books/{book} <-- viewing book
- Get /books/create <-- form for creating book
- Post /book/store <-- persist the book

Currently when validation fails on POST `/books/store` it will redirect to GET `/books/store` which does not exist, so the router will run it through GET `/books/{book}`, which I think, not most people expect  (and cause the route model binding initializer to fail (`Fatal error: Uncaught TypeError: Tempest\Http\RouteBindingInitializer::initialize(): Return value must be of type object, null returned`)).

I expected to be redirected back to `/books/create`, and that is how laravel handles it by default (redirects to whats in the `Referer` header or gets the previous location from the session, [see here](https://github.com/laravel/framework/blob/25873116d90107414a21ab22a3b20e5a802f9a26/src/Illuminate/Foundation/Http/FormRequest.php#L190)).

I did some tests and it seems to work when the Referer header is used as the redirect uri. Maybe this should be configurable in the request somehow? (how to handle when no referer or no previous url?)

(When I checked some tests they tested it redirected back to the uri that "failed")

And I guess if you send a json request you just want some json response with the errors?

### Steps to Reproduce

Create two routes:
- Get /books/create <-- form for creating book
- Post /book/store <-- persist the book

And a request with some validation.

post from the create view to store

**Comment by brendt** [comment]
Fixed on main :)
