### ISSUE TITLE
[Bug]: tempest serve without port

### ISSUE THREAD

**Issue by brendt** [tempestphp/tempest-framework#537]
### Tempest Version

1.0-alpha2

### PHP Version

8.3

### Operating System

MacOS

### Description

`./tempest serve 0.0.0.0` gives an error because the port is required. We should add `:8000` if no port is set.

### Steps to Reproduce

/

**Comment by aidan-casey** [comment]
@brendt - I wonder if we should have these be separate parameters to the command/method?

**Comment by hanieas** [comment]
@brendt 
Could we consider adding $port as an argument to the `ServeCommand::__invoke` function? This would automatically handle the port definition, allowing the command to be run with or without specifying a port.

I suggest modifying the ServeCommand like this:
``` php
public function __invoke(string $host = 'localhost', int $port = 8000, string $publicDir = 'public/'): void
{
    passthru("php -S $host:$port -t $publicDir");
}
```
This would allow the command to work as follows:

Without specifying a port:
./tempest serve --host=localhost

With a specific port:
./tempest serve --host=localhost --port=8082

This approach provides more flexibility and handles the port argument dynamically. What do you think?

**Comment by aidan-casey** [comment]
@hanieas - This is definitely the way to do it. Are you willing to submit a PR?

**Comment by hanieas** [comment]
@aidan-casey - Sure! I'll submit PR.

**Comment by aidan-casey** [comment]
Thank you, @hanieas!

**Comment by hanieas** [comment]
@aidan-casey - The [PR](#546 ) is submitted.
I'll send another PR on docs shortly.

**Comment by aidan-casey** [comment]
Thank you!
