### ISSUE TITLE
[Bug]: View renderer camelCases all html attributes

### ISSUE THREAD

**Issue by NeoIsRecursive** [tempestphp/tempest-framework#583]
### Tempest Version

dev-main

### PHP Version

8.3

### Operating System

MacOS

### Description

It seems like html element attributes are camelCased after rendering, for example `data-theme` becomes `dataTheme`.

### Steps to Reproduce

I have created a test for this #459.

**Comment by brendt** [comment]
Fixed with https://github.com/tempestphp/tempest-framework/pull/585 on dev-main
