### ISSUE TITLE
[Bug]: Nullable properties not seen as nullable by TypeReflector

### ISSUE THREAD

**Issue by ainesophaur** [tempestphp/tempest-framework#594]
### Tempest Version

1.0-alpha2

### PHP Version

8.3

### Operating System

MacOS

### Description

After updating from alpha1 to alpha2 in a basic todo app I started getting `MissingValue` exceptions when accessing null database values in a model where the property is nullable and had a default value of null. 

```php
final class Todo implements DatabaseModel
{
    use IsDatabaseModel;

    public function __construct(
        public string        $title,
        public ?string $description = null,
    )
    {}
}
```

In tracing from `QueryToModelMapper` > `ClassReflector` > `TypeReflector` I found that `TypeReflector` would only set the `definition` for my description field as `string` and not `?string` or the union `null|string`. 

I submitted #591  to confirm the issue. I have a PR to submit with a fix but Im waiting for this to get confirmed.

### Steps to Reproduce

```php

final class Todo implements DatabaseModel
{
    use IsDatabaseModel;

    public function __construct(
        public string        $title,
        public ?string $description = null,
    )
    {}
}

Todo::create(title: "test");
ll(Todo::query()->first()->description); //throws MissingValue
```php

**Comment by brendt** [comment]
I fixed it in https://github.com/tempestphp/tempest-framework/pull/591 :)
