### ISSUE TITLE
[Bug]: Rector is broken

### ISSUE THREAD

**Issue by brendt** [tempestphp/tempest-framework#597]
### Tempest Version

1.0-alpha2

### PHP Version

8.3

### Operating System

MacOS

### Description

Rector doesn't work

### Steps to Reproduce

Run rector locally

**Comment by brendt** [comment]
See https://github.com/rectorphp/rector/issues/8864

**Comment by PierreThiollent** [comment]
Hello,

I wanted to try to fix the bug but I can't reproduce it, Rector works correctly. The mentioned issue has been closed so I think we can close this one too 😊

**Comment by aidan-casey** [comment]
Sorry, yes this can be closed. 🙂
