### ISSUE TITLE
Event bus

### ISSUE THREAD

**Issue by brendt** [tempestphp/tempest-framework#6]
We need an event bus implementation similar to our command bus implementation

**Comment by aidan-casey** [comment]
@brendt - Happy to assist with this if there is a general direction you want to take it. Just thinking out loud here, I'd love to see an implementation that allows cross platform events pulled from a queue or something.

**Comment by brendt** [comment]
That's a good idea. As a first step I imagine the `EventBus` to be pretty similar to the `CommandBus`, the difference being that there are multiple possible handlers per event. From a user's point of view, the API should be familiar:

```php
final readonly class MyEventHandler
{
    #[EventHandler]
    public function handle(MyEvent $event): void
    { … }
}
```

```php
$eventBus->dispatch(new MyEvent());
// or
event(new MyEvent());
```

Pulling from external sources is a concern outside the scope of the eventbus, I think. It should be a cron job or webhook of some kind that either pulls information or gets information pushed to it about new events. That's my vision, what do you think?

**Comment by aidan-casey** [comment]
@brendt - Agreed on the API, easy enough.

I'm thinking this is actually something we need to consider in the creation of the event bus and potentially backfill to the command bus. Tempest shouldn't just be able to receive events from other apps, but send them.

Probably the easiest way to minimally address this is to allow the handoff to a message broker to handle most of the work and have a native Tempest driver that just works out of the box.

**Comment by brendt** [comment]
How I envisioned over-the-wire events and commands is by introducing either a handler or middleware that detects which events and commands should be sent over the wire, and does so. 

I don't think Tempest itself should act as a message broker for a 1.0 release, although I would like to build something similar to Laravel Horizon (for commands and events, not "jobs") in the future. There are a lot of decisions to make in designing such a system though, and I wouldn't want it to distract us from a 1.0 release.

**Comment by aidan-casey** [comment]
@brendt - Hear me out... Tempest is not the message broker, but supports different drivers for the message bus. This would allow you to have some out of the box support for RabbitMQ, Redis, etc. and I would guess in the long run, encourage some more advanced messaging features by opening the possibilities.

See below for an example. I know there is some redundancy between the actual driver and bus, but that is just to allow it to be configurable.

```php
// Tempest could default to an in-memory event bus driver
// while allowing options for things like RabbitMQ.

interface EventBusDriver
{
    public function dispatch(string $event, object $payload): void;

    public function subscribe(string $event, callable $handler): void;
}

// The driver in use is configurable so it's not hard to swap.

final readonly class EventBusConfig
{
    public function __construct(public EventBusDriver $driver)
    {}
}

// The event bus is simply handing off to the right driver. This opens options in the long
// run for routing, etc. if it is decided to belong in Tempest (though it might not!)

final class EventBus
{
    public function __construct(private readonly EventBusConfig $config)
    {}

    public function dispatch(object $event): void
    {
        // We could simply pass to the driver, but this allows
        // less work since Tempest is identifying the event name, etc.
        // It may or may not be a concern here.
       $name = ...;

        $this->config->driver->dispatch($name, $event);
    }

    public function subscribe(string $event, callable $handler): void
    {
        $this->config->driver->subscribe($event, $handler);
    }
}

// You can specify some metadata for serialization or something.

#[Event(alias: 'pet.adopted')]
final readonly class PetAdopted
{
    public function __construct(public string $name)
    {}
}
```

**Comment by brendt** [comment]
Interesting! This will need some further discussing :) A couple of preliminary thoughts at 6 AM (so I might miss some obvious things):

**1.** It seems that your implementation would only support one active driver at any given point? I think that wouldn't suffice, since I might want to send events to multiple places, depending on which event we're dealing with. In an ideal world, this configuration of "which event goes where" shouldn't be the event's concern, although we might end up allowing the possibility to do so for convenience

**2.** A core principle of Tempest's discovery (at the moment) is that handlers are discovered, and not their subjects. It's the controller method, the console command, and the command handler that we discover, not the request, the command, or the event. I like this consistency, and would like to stick with it if possible. Essentially it means that "subject" objects are simple objects: request objects, command objects, event objects; they represent data and nothing more. 

In case of events, it makes sense to have some kind of MetaData attribute to attach meta data to an event object — that's totally fine; but I would like them to stay data objects that don't need to know about the inner workings of the framework. 

All in all, that means that I don't think a `#[Event]` attribute or `Event` interface makes sense if it would be used to tie those objects to Tempest, we need to be careful of that. Writing this down, I realise this actually goes back to my first point, where I describe "the ideal world" in which an event itself shouldn't be concerned with how it's routed and to where. The event is a data object, and nothing more.

Anyway, I hope that makes sense 😁

**3.** Keeping this principle in mind, for me it makes more sense that routing events to different places would be handled by either middleware or handlers. But that's just a slight personal preference, and I don't oppose the idea of drivers. The only thing that seems more easy to solve with middleware and/or handlers is the problem of "one driver for everything". Some events might be internal events, others should be sent to <message broker of your choice>, others should be sent to another microservice over HTTP, some should be sent to different places, … I think handling this with dedicated handlers would be easier to understand, and more flexible.

All in all, not opposing the idea, and I think it'd be a nice addition in the framework, we just need to make sure all the details are carefully thought through.

**Comment by aidan-casey** [comment]
> It seems that your implementation would only support one active driver at any given point? I think that wouldn't suffice, since I might want to send events to multiple places, depending on which event we're dealing with. In an ideal world, this configuration of "which event goes where" shouldn't be the event's concern, although we might end up allowing the possibility to do so for convenience

So, in this scenario, Tempest is really not acting as the bus itself, but is handing off to a separate implementation defined by the driver (in memory, RabbitMQ, etc.). This is partly for laziness and simplicity, but also practicality when getting into multi-language event requirements. If I want to get Tempest and a .NET application talking, it's not very helpful for all the routing to be in PHP.

Food for thought. 🙂

> In case of events, it makes sense to have some kind of MetaData attribute to attach meta data to an event object — that's totally fine; but I would like them to stay data objects that don't need to know about the inner workings of the framework.

If I serialize an event in .NET and send it to my bus, Tempest has to be able to understand how to unserialize it. Totally heard on wanting them to be unaware of the framework, that just means you have to map/alias them elsewhere which takes away from the simplicity. Curious to hear your ideas here!

> Some events might be internal events, others should be sent to , others should be sent to another microservice over HTTP, some should be sent to different places

This goes to the "what is the bus?" conversation I think. I'm not sure I'd agree with the idea of "internal events" vs. "microservice events" but that's more of an application implementation detail.

**Comment by aidan-casey** [comment]
@brendt - Some further thoughts below.

For the purpose of aligning terminology, we are really talking about _inside_ vs. _outside_ (integration) events. [This](https://learn.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/domain-events-design-implementation) Microsoft article is helpful in defining those.

Looking around, it seems like most people are taking the approach I define above, where some form of driver is defined, but they are differentiating between local events and integration ones.

ABP has a [`local event bus`](https://docs.abp.io/en/abp/8.0/Local-Event-Bus) and a [`distributed event bus`](https://docs.abp.io/en/abp/8.0/Distributed-Event-Bus).

Symfony has an [`event dispatcher`](https://symfony.com/doc/current/components/event_dispatcher.html) and a [`messenger`](https://symfony.com/doc/current/messenger.html).

From a user-friendly position, I don't love the idea of splitting these up. One idea might be to introduce the idea of "transports" similar to [Wolverine](https://wolverine.netlify.app/guide/messaging/transports/rabbitmq/) and allow the forwarding of an event to a specific transport using middleware and/or the specification of the transport when dispatching. See below for an example:

```php
$eventBus = new EventBus(
    new EventBusConfiguration(
        transports: [
            new EventBusTransport(
                name: 'rabbit-mq',
                driver: new RabbitMqDriver(...)
            )
        ]
    )
);


// Basically just checks if the event is related to something
// and uses the event bus to forward it to a transport.
$eventBus->addMiddleware(
    new EventForwarderMiddleware(
        transport: 'rabbit-mq',
        topic: 'pets.*'
    )
);

// This just gets dispatched to the 'rabbit-mq' transport.
event(
    event: new PetWasAdopted(name: 'Fido'),
    transport: 'rabbit-mq' // Defaults to 'local' or 'default' or something
);

// This would be sent to 'local' and forwarded to 'rabbit-mq'
// because of the forwarder middleware we set up.
event(new PetWasAdopted(
    name: 'Fido'
));
```

**Comment by brendt** [comment]
> From a user-friendly position, I don't love the idea of splitting these up.

Exactly my idea 😁

From the options we've discussed, I think defining transports makes the most sense. It's also closest in terminology in what we want to do.

_However_, one remark I still want to give, please indulge me for a moment 😁

An event can have zero, one, or multiple handlers, right? That's one of the core principles of event-driven systems. It's also one of the key differences between a command and an event; they are two specialised forms of messages, each with their own goals.

Let me know if you agree up until this point 😁

Ok so, events can have zero, one, or multiple handlers. That means a given event can have internal handlers, as well an external ones. This leads to my first remark: we'd need the possibility to define multiple transports.

My second remark is actually much more important: the strength of using events is indirectness: you don't need to know what happens when dispatching an event, you only need to know about the event itself. Having to define a transport when dispatching an event makes for a tight coupling between events and their handlers — after all, you're choosing which subset of handlers will be able to handle this event, when you're dispatching it.

I don't like that design, that's a leaky abstraction (first time I can accurately use that term, I believe). I think our goal should be to have this API for the end users, in all cases:

```php
dispatch(new EventHappened());
```

This is the API we'll have to deal with, and if we want Tempest to support multiple transports, we'll need to find a way to make it work within these constraints.

There are three ways I can think of:

1. Define transports on the event object:

```php
#[Event(Transport::Internal(), Transport::RabbitMq())]
final readonly class EventHappened { … }
```

2. Have events implement an interface for external transports:

```php
final readonly class EventHappened implements SendToRabbitMq { … }
```

3. Keep events as simple data objects, and do the mapping via middleware:

```php
final readonly class RabbitMqMiddleware implements EventMiddleware
{
    public function __construct(
        private array $eventsForRabbitMq,
        private RabbitMq $rabbitMq,
    ) {}

    public function __invoke(object $event, callable $next): void
    {
        if (isset($eventsForRabbitMq[$event::class])) {
            $rabbitMq->send($event);
        }
        
        $next($event);
    }
}
```

wydt?

**Comment by aidan-casey** [comment]
@brendt - I think you are close to something on option 3, but I am going to suggest it is not done via middleware, but via the concept of transports we are discussing.

I suggest we support the following:

- **Transports**: A driver (for lack of a better term) that the event bus uses to interact with queues and topics. Multiple can be registered, but Tempest ships with one defined by default that handles all topics. We _might_ have to split these into `SynchronousTransport` and `AsynchronousTransport` interfaces.
- **Queues**: A channel for events to go to
- **Topics**: Specific events that a listener might subscribe to (e.g., `pets.*`)

In the configuration of a transport, we can define what topics we are interested in and/or handle some basic routing to queues. For example:

```php
new GenericEventBus(
    new EventBusConfig(
        transports: [
            // Tempest transport registered by default,
            // sufficient for most.
            new Transport(
                driver: new TempestSynchronousTransport(),
                topics: [
                    Topic::all(),
                ]
            ),

            // RabbitMQ transport which allows cross-platform event handling
            // but restricted to pets!
            new Transport(
                driver: new RabbitMqDriver(host: 'localhost'),
                topics: [
                    Topic::all(), // Basically Topic::new('*')->toQueue('*'),
                    Topic::new('pets.*')->toQueue('pets'),
                ]
            ),
        ]
    )
);
```

**Comment by brendt** [comment]
I like this approach the most! I assume we'd tag event topics with an attribute?

**Comment by aidan-casey** [comment]
That's the next thing to figure out. 😅

**Comment by brendt** [comment]
```php
#[Topic('pets.cats')]
final readonly class ItHappened
{ /* … */ }
```

Something like that?
