### ISSUE TITLE
Optimize Route matching

### ISSUE THREAD

**Issue by N-Silbernagel** [tempestphp/tempest-framework#60]
Matching the request URL to a route is currently done via a looped Regex.

[Nikita wrote](https://www.npopov.com/2014/02/18/Fast-request-routing-using-regular-expressions.html) about how using one Regex to match all routes can speed up Route matching, which is also used in Symfonys Router.

Is this a change that would be of interest to the framework?

**Comment by brendt** [comment]
btw, we could also switch to using FastRoute, it's a tried and tested package. But it's also fun trying to solve this ourselves :)

**Comment by N-Silbernagel** [comment]
I would love to see if I can implement it, might take me 1-2 weeks to find the time.

**Comment by brendt** [comment]
I think that's fine. The current implementation works for now, and it's all internal code anyway, it shouldn't have an impact on any public API. 

So feel free to spend some time on it when you have the chance 👍
