### ISSUE TITLE
[Bug]: can not run tests, root path is not correct

### ISSUE THREAD

**Issue by Treggats** [tempestphp/tempest-framework#602]
### Tempest Version

v1.0.0-alpha.1 / dev-main (e00d0cd35f8c07fde1cdae549c70c7605647fff8)

### Example repo
https://github.com/Treggats/process-hour-slab/blob/tests-example/

### PHP Version

8.3

### Operating System

Linux, MacOS

### Description

running any basic test fails.

```shell
Tempest\Core\DiscoveryException: Could not locate /Users/Projects/project/vendor/tempest/framework/src/Tempest/Framework/Testing/../../vendor/composer/installed.json, try running "composer install"
```

[example CI run ](https://github.com/Treggats/process-hour-slab/actions/runs/11420696286/job/31776697460)

### Steps to Reproduce

run this test `tests/Feature/HomeControllerTest.php`
`vendor/bin/phpunit tests`

**Comment by Treggats** [comment]
updated the branch to use my own `TestCase`

```
1) Tests\Feature\HomeControllerTest::homepage_route_gives_http_ok_response
* Test code or tested code did not remove its own error handlers

* Test code or tested code did not remove its own exception handlers

/home/runner/work/process-hour-slab/process-hour-slab/tests/Feature/HomeControllerTest.php:14
```

https://github.com/Treggats/process-hour-slab/actions/runs/11425924424/job/31788199551

**Comment by Treggats** [comment]
Tracked it down to. `\Tempest\Core\GenericExceptionHandlerSetup` line 22
```php
// Console
if (PHP_SAPI === 'cli') {
    (new Collision())->register();

    return;
}
```

If I disable Collision, then the tests will run no problem.

**Comment by brendt** [comment]
I still need to check this out, but I aim to have it fixed before alpha.3

**Comment by brendt** [comment]
Is this still an issue? I tried out your repo with dev-main, and don't get this error

**Comment by brendt** [comment]
I do get a warning though:

```
1) Tests\Feature\HomeControllerTest::homepage_route_gives_http_ok_response
* Test code or tested code did not remove its own error handlers

* Test code or tested code did not remove its own exception handlers
```

**Comment by brendt** [comment]
I found this issue: https://github.com/laravel/framework/issues/49502 

You could add this in your tearDown method:

```
        restore_error_handler();
        restore_exception_handler();
```

I eventually want to remove collision and switch back to our custom console exception handler, which will fix this. I'll create an issue and bump the priority

**Comment by Treggats** [comment]
> I found this issue: https://github.com/laravel/framework/issues/49502 
> 
> 
> 
> You could add this in your tearDown method:
> 
> 
> 
> ```
> 
>         restore_error_handler();
> 
>         restore_exception_handler();
> 
> ```

Ah nice, was looking for something like this.

I'll give it a second try when I get home.

> I eventually want to remove collision and switch back to our custom console exception handler, which will fix this. I'll create an issue and bump the priority
