### ISSUE TITLE
[Bug]: console - cannot use standalone: class already in use 

### ISSUE THREAD

**Issue by homersimpsons** [tempestphp/tempest-framework#605]
### Tempest Version

dev-main

### PHP Version

8.3

### Operating System

Linux

### Description

I want to setup a console application, following https://tempestphp.com/docs/console/getting-started/

I run composer require `tempest/console:dev-main` and create a `main.php` file and an `src/InteractiveCommand.php` with the correct psr-4 setup et al.

When I run the application with `php ./main.php`, I have the following error:

```
Cannot declare class App\InteractiveCommand, because the name is already in use

at src/InteractiveCommand.php:8
```

It looks like the component tries to load my class twice (maybe once for discovery and once tu run it?).

Follow-up of #601

### Steps to Reproduce

1. `composer require tempest/console:dev-main`
2. (copy the files)
4. `php ./main.php`

**Comment by brendt** [comment]
Could you maybe push your repo somewhere for me to take a look? I did test this, and couldn't reproduce it after my fix. But maybe I missed something.

**Comment by homersimpsons** [comment]
> Could you maybe push your repo somewhere for me to take a look? I did test this, and couldn't reproduce it after my fix. But maybe I missed something.

Yes, here is the repository: https://github.com/homersimpsons/tempest-console-605
