### ISSUE TITLE
Cleanup `PathHelper::root`

### ISSUE THREAD

**Issue by brendt** [tempestphp/tempest-framework#615]
It might have no use anymore

**Comment by innocenzi** [comment]
I was using it initially for the publishing logic, but refactored it with the new `Composer` stuff, and forgot to remove it. You can safely remove it from the PR 👍

**Comment by NeoIsRecursive** [comment]
Does this mean that #607 isn't something Tempest want to provide?

**Comment by brendt** [comment]
Yeah we do, just not with that added PathHelper function, but I don't think your PR did, so it's all fine
