### ISSUE TITLE
`ArrayHelper::sort`

### ISSUE THREAD

**Issue by brendt** [tempestphp/tempest-framework#631]
To sort items in an array

**Comment by gturpin-dev** [comment]
Just link the "main TODO" of array helpers methods here as this method is a part of it 😄 
https://github.com/tempestphp/tempest-framework/issues/543

Feel free to give an input if I haven't pushed something yet 😃

**Comment by brendt** [comment]
Basic sort was added by #642, but we're also going to need sort desc, ksort, and usort

**Comment by Bapawe** [comment]
Hey @brendt , I started working on this earlier this week but paused when I saw that someone else had already submitted a pull request ([#642](https://github.com/tempestphp/tempest-framework/pull/642)). If you’re open to my approach, just let me know, and I’ll pick it back up and submit my own pull request.

https://github.com/tempestphp/tempest-framework/compare/main...Bapawe:tempest-framework:array-sort-helpers

**Comment by gturpin-dev** [comment]
> Hey @brendt , I started working on this earlier this week but paused when I saw that someone else had already submitted a pull request ([#642](https://github.com/tempestphp/tempest-framework/pull/642)). If you’re open to my approach, just let me know, and I’ll pick it back up and submit my own pull request.
> 
> [main...Bapawe:tempest-framework:array-sort-helpers](https://github.com/tempestphp/tempest-framework/compare/main...Bapawe:tempest-framework:array-sort-helpers)

I like this approach personnally.
Maybe replace the `ByCallback` to `By` ? but it's details.

**Comment by Bapawe** [comment]
Oke cool, you can assign this ticket to me if you want, i'll create a PR soon.
