### ISSUE TITLE
[Bug]: Class "Tempest\EventBus\EventBus" does not exist when running commands

### ISSUE THREAD

**Issue by guilhermeaiolfi** [tempestphp/tempest-framework#635]
### Tempest Version

1.0-alpha1

### PHP Version

8.3

### Operating System

Windows

### Description

Hi.

Currently I have a symfony Console to manage my application (that was developed using a custom framework). But after watching some videos of Brent I thought that maybe using tempest console would be nice. I've followed the commands here: https://tempestphp.com/console/. 

First, ```--stability alpha``` didn't work.  Composer doesn't seem to support that. At least on windows. But I was able to workaround it setting it in the ```composer.json```. But when running:

```./vendor/bin/tempest hello:world Brent```

I've got this error:

```
Fatal error: Uncaught ReflectionException: Class "Tempest\EventBus\EventBus" does not exist in www\tempest-console-demo\vendor\tempest\reflection\src\ClassReflector.php:28
Stack trace:
#0 www\tempest-console-demo\vendor\tempest\reflection\src\ClassReflector.php(28): ReflectionClass->__construct('Tempest\\EventBu...')
```

### Steps to Reproduce

1. Install tempest/console in a empty project
2. Create a command class
3. Run the command

**Comment by brendt** [comment]
When I perform these steps, I get no error, but I'm running dev-main. Are you running alpha.2 or dev-main? 

Alpha 2 does have some issues with installing individual components, which will be fixed in alpha 3. Could you try requiring dev-main instead and retry?

Also, for the `--stability alpha` flag: that'll be removed from the docs soon :)

**Comment by brendt** [comment]
Gonna close this one, but feel free to reopen with followup if needed.

**Comment by guilhermeaiolfi** [comment]
Sorry it took me so long. But using dev-main worked. And it worked great. 

I think if it can work without the discovery part and slim down the dependencies a bit, it can take the crown from symfony/console as the solution for command apps.  @brendt and the team accomplished something really great here. Congratulations.

**Comment by brendt** [comment]
Discovery is totally optional, btw, but it's nowhere documented yet how to do it, and it will probably take a couple of steps, but it's definitely possible. 

Is there a reason you don't want discovery?

**Comment by guilhermeaiolfi** [comment]
For this project, I would be more confortable with a little bit less magic. And I guess there is a penalty (performance wise) attached to it. The latter probably is not a problem because it is cached anyway.

But in the future I would like to control which commands could be added to the app based on the user or a feature flag, and discovery would be in the way.

**Comment by brendt** [comment]
Fair enough, it's not super high on the priority list to make it as smooth as possible without discovery, but it's definitely possible and you can already hack it together today. The only thing you really need to be aware of is how the kernel is bootstrappen (see `\Tempest\Core\Kernel`). You can create your own version without loading discovery, and it should work fine.
