### ISSUE TITLE
How to set a base URI?

### ISSUE THREAD

**Issue by steffans** [tempestphp/tempest-framework#637]
### Tempest Version

1.0-alpha1

### PHP Version

8.3

### Operating System

MacOS

### Description

Im running the tempest project from a subfolder in my htdocs directory. Is there a way to set a base URI for example to `/tempest-app/public` in order to make `/` root route match correctly?

I have found the env('BASE_URI') setting in the AppConfig but it is only used in GenericRouter::toUri() but not when matching the incoming request.

### Steps to Reproduce

Just create a tempest app in a subfolder of your webserver.

**Comment by brendt** [comment]
If I understand you correctly, you're talking about a base path, right? A string that's always prepended to the path. You could make a middleware for it that will always prepend `/tempest-app/public` to the request's path. That's one option. 

If someone wants to PR such a middleware and config option, I'd probably merge it. However, it's not super high on my personal priority list.

**Comment by steffans** [comment]
The base path its already in set in the `/tempest-app/public` in the current requests path but this means the `/` root route wont match the request path resulting a 404.

To solve this either all routes need to be prefixed with the base path in order to match correctly or the base path has to be removed from the current request path when matching the route in [GenericRouter::matchStaticRoute()](https://github.com/tempestphp/tempest-framework/blob/972595c371987c378b83cf09de414f9f571c345a/src/Tempest/Http/src/GenericRouter.php#L214) and [GenericRouter::matchDynamicRoute()](https://github.com/tempestphp/tempest-framework/blob/972595c371987c378b83cf09de414f9f571c345a/src/Tempest/Http/src/GenericRouter.php#L223).

**Comment by brendt** [comment]
Do I get it right that you want _some_ URLs to be prefixed? This is where custom route attributes could help: https://tempestphp.com/docs/framework/controllers/#custom-routes

```php
#[Attribute]
final readonly class BaseRoute extends Route
{
    public function __construct(string $uri, Method $method = Method::GET)
    {
        parent::__construct(
            uri: '/tempest-app/public' . $uri,
            method: $method,
        );
    }
}
```

Then use that one in your controllers:

```php
class MyController
{
    #[BaseRoute('/hello-world')]
    function index(): Response {}
}
```

Gonna close this issue, but feel free to provide feedback if I misunderstood :)
