### ISSUE TITLE
[Bug]: Not working with multiple php version installed on window

### ISSUE THREAD

**Issue by vantruong1898** [tempestphp/tempest-framework#645]
### Tempest Version

1.0-alpha2

### PHP Version

8.3

### Operating System

Windows

### Description

My computer install multiple php version
Command : Version
php: default PHP 8.2.3
php81: PHP 8.1
php82: PHP 8.2
php83: PHP 8.3

Run command: php83 tempest serve => error 500

### Steps to Reproduce

Command: php83 tempest serve
=> PHP 8.2.3 Development Server (http://localhost:8000) started
PHP 8.2.3 is default php version on my computer

**Comment by brendt** [comment]
Could you provide the PHP error log output? You should be able to run `tempest tail`, next run `tempest serve` in another terminal session, refresh, and the error should be shown.

**Comment by Treggats** [comment]
Also, how are these versions installed?

@brendt I'll try to reproduce on my Windows machine. I have Herd with multiple PHP versions.
