### ISSUE TITLE
Tempest "Modules"

### ISSUE THREAD

**Issue by aidan-casey** [tempestphp/tempest-framework#65]
Currently Tempest is structured where interfaces are in the `Tempest\Interface` directory. I suspect this is to give similar ability to Laravel with the contracts package.

I am proposing that alongside #47 we restructure the `Tempest` namespace a little bit so that it _could be_ modularized in the future (separate packages for orm, etc).

The proposed naming structure is shown below with some examples of naming conventions as well due to the conflicts it would create.

```bash
src/
├── Console/
│   ├── Formatting/
│   │   ├── ConsoleFormatter.php - Interface
│   │   └── HandlesConsoleFormatting.php - Trait
│   ├── Input/
│   │   ├── ConsoleInput.php - Interface
│   │   └── HandlesConsoleInput.php - Trait
│   ├── Output/
│   │   ├── ConsoleOutput.php - Interface
│   │   └── HandlesConsoleOutput.php - Trait
│   ├── ConsoleFormatter.php - Default Implementation
│   ├── ConsoleInput.php - Default Implementation
│   └── ConsoleOutput.php - Default Implementation
└── View/
    ├── Engine/
    │   ├── IsView.php - Trait
    │   └── View.php - Interface
    └── View.php - Default Implementation
```

Now it is important to note that when importing the `View` interface and instantiating a new `View` class, there is a conflict that has to be aliased. (This is true for other frameworks, like Laravel, as well but does make things awkward).

We could restructure naming to be something like `TempestView` or `HtmlView`, but that is potentially less elegant.

In theory everything could adopt discovery to initialize itself and simply be installed (or split out to) a separate package. Package dependencies could simply require the modules they absolutely need.

**Comment by brendt** [comment]
The alias part is a no-go for me, this is something I really dislike about Laravel and some previous frameworks I worked with. I believe negatively impacts DX for no good reason. 

- Interfaces should have the shortest name
- Concrete implementations should make sense, but not collide with the interfaces
- Trait names are already discussed in #47 , and are just a matter of implementing

I don't have a strong opinion on the module structure — one of Tempest's goals is to not make a decision here 😁 There's only one thing I think is important in this regard: if we decide that moving interfaces to modules is preferred (I can see why), then I would say they should live in the root directory of the module though, and not deeper within subfolders.

I think it's a matter of specificity: the closer a class or interface is to the root folder of the framework, the more interaction between it and users. I think that convention will make the most sense in the long run, as people will instinctively know where they can find something.

**Comment by aidan-casey** [comment]
@brendt - actually no disagreement from me on any of this. The nested directory structure depicted here comes purely as a solution to having `View` and `View` in the same folder. 😅

Is it your inclination to keep the `GenerixXxxx` where a default is provided and an actual type (e.g., `InMemoryXxxx`) is not inferable?

All that cleared up, if you're not opposed to me taking a stab at rearranging this, I'll submit a PR.

**Comment by brendt** [comment]
> Is it your inclination to keep the `GenerixXxxx` where a default is provided

For now, until we come up with a better name, I think so, yes.
