### ISSUE TITLE
[Bug]: Package config overwrites app config

### ISSUE THREAD

**Issue by NeoIsRecursive** [tempestphp/tempest-framework#658]
### Tempest Version

dev-main

### PHP Version

8.3

### Operating System

MacOS

### Description

I have been tinkering with an Inertiajs adapter for tempest ([here](https://github.com/NeoIsRecursive/inertia-tempest) if anyone's interested).

The issue is that the default config included by the package overwrites the config defined by the application.

I think this is because of the order `discoveryLocations` are discovered:

```php
[
  ...$this->kernel->discoveryLocations,
  ...$this->discoverCorePackages(),
  ...$this->discoverAppNamespaces(),
  ...$this->discoverVendorPackages(),
]
```
If I swap `$this->discoverAppNamespaces()` and `$this->discoverVendorPackages()` it works as expected.

One other solution is to make some sort of system that prioritizes "app config" paths within the `LoadConfig` class, but that would mean requiring the file to get the type of the config and then do some mapping.

I tinkered some with that and came up with this, but I'm not really sure about the performance impact this would have and the instantiation just to get the type could have implications I guess (that I also assume exist now, since each config is registered even if it is to be overwritten later):
 
```php
$configPaths = $this->cache->resolve(
    'config_cache',
    function () {
        $vendorConfigPaths = [];
        $appConfigPaths = [];

        // Scan for config files in all discovery locations
        /** @var DiscoveryLocation $discoveryLocation */
        foreach ($this->kernel->discoveryLocations as $discoveryLocation) {
            $directories = new RecursiveDirectoryIterator($discoveryLocation->path, FilesystemIterator::UNIX_PATHS | FilesystemIterator::SKIP_DOTS);
            $files = new RecursiveIteratorIterator($directories);

            /** @var SplFileInfo $file */
            foreach ($files as $file) {
                if (! str_ends_with($file->getPathname(), '.config.php')) {
                    continue;
                }

                if ($discoveryLocation->namespace === src_namespace() . '\\') {
                    $appConfigPaths[] = $file->getPathName();
                    continue;
                }

                $vendorConfigPaths[] = $file->getPathname();
            }
        }

        $configPaths = [];

        foreach ($vendorConfigPaths as $path) {
            $configPaths[(require $path)::class] = $path;
        }

        foreach ($appConfigPaths as $path) {
            $configPaths[(require $path)::class] = $path;
        }

        return $configPaths;
    }
);
```

### Steps to Reproduce

Install a tempest package (or make a local one) that has a default config.
Then make a "local" config file.

**Comment by brendt** [comment]
That's definitely a bug, I fixed it on dev-main :)
