### ISSUE TITLE
[Bug]: View echo tags don't work in normal HTML attributs

### ISSUE THREAD

**Issue by brendt** [tempestphp/tempest-framework#665]
### Tempest Version

1.0-alpha.3

### PHP Version

8.3

### Operating System

MacOS

### Description

```
<div class="{{ $class ?? '' }}
```

### Steps to Reproduce

/

**Comment by nhedger** [comment]
Wouldn't it be better to just do the following in this case ?

```html
<div :class="$class ?? ''"></div>
```

In Vue 3, they deprecated interpolation within attributes, and I believe part of it was to reduce confusion.

**Comment by brendt** [comment]
That's a good consideration. What you describe is already possible 🤔

It might just be a matter of documenting then that `<div class="{{ $class ?? '' }}` isn't allowed

**Comment by nhedger** [comment]
Also, it makes more sense if we say that anything between those quotes should be valid PHP.

**Comment by brendt** [comment]
That's already implelented, both `<?=`, <?php`, `{{`, and `{!!` aren't allowed in expression attributes
