### ISSUE TITLE
[Bug]: auth package user model uses invalid class string for userPermissions property

### ISSUE THREAD

**Issue by ainesophaur** [tempestphp/tempest-framework#695]
### Tempest Version

1.0-alpha3

### PHP Version

8.3

### Operating System

MacOS

### Description

After installing the auth package a fatal error is thrown when attempting to create a user and grant permission. However, the issue isn't scoped only to granting permission, it occurs whenever the user model is trying to load the relation for 'userPermissions.permission' (IE, `SessionAuthenticator::currentUser()` will trigger the error)

When *HasManyRelation.php* is checking for the inverseProperty, it fails to recognize the public `$userPermissions` property on the `User` model because the docblock refers to `\Tempest\Auth\Install\UserPermission[]`, but the models are installed to `App\Auth`.  Specifically, `$this->relationModelClass->getPublicProperties()` is empty when $userPermission has the default `@var` tag 

```
Error: Call to a member function getName() on null
at vendor/tempest/framework/src/Tempest/Database/src/Builder/Relations/HasManyRelation.php:38
at vendor/tempest/framework/src/Tempest/Database/src/Builder/ModelDefinition.php:35
at vendor/tempest/framework/src/Tempest/Database/src/Builder/ModelQueryBuilder.php:189
```

```php
public function __construct(
//...
/** @var \Tempest\Auth\Install\UserPermission[] $userPermissions */
public array $userPermissions = [],
) {}
```

fixed by updating the `@var` tag

```php
public function __construct(
//...
/** @var \App\Auth\UserPermission[] $userPermissions */
public array $userPermissions = [],
) {}
```

Just in case anyone comes across it in the mean time.

### Steps to Reproduce

1. Install auth package

`./tempest install auth`
`./tempest migrate:up`

2. Confirm the default user model has a `@var` tag for `$userPermissions` referring to `\Tempest\Auth\Install\UserPermission[]`

3. Create a user and attempt to give permission

```php
(new User(
            name: 'Travis Sheldon',
            email: 'travis@ownwebnow.com',
        ))
            ->setPassword('password')
            ->save()
            ->grantPermission('admin') //failure is triggered here
        ;
```

**Comment by brendt** [comment]
Should be fixed on dev-main now :)
