### ISSUE TITLE
Brent. 

### ISSUE THREAD

**Issue by luizcmarin** [tempestphp/tempest-framework#75]
Hi brent. Do you usually read and respond to emails?

**Comment by aidan-casey** [comment]
Hey, @luizcmarin! I am going to go ahead and close this issue just in interest of keeping this repository clean as we sort through issues.

@brendt has his email on his website (stitcher.io) and you can email him there. 🙂

**Comment by brendt** [comment]
I've seen your email, don't worry :) I'll answer it soon
