### ISSUE TITLE
[Bug]: Http Status Code 418 has the wrong description

### ISSUE THREAD

**Issue by aidan-casey** [tempestphp/tempest-framework#778]
### Tempest Version

1.0-alpha4

### PHP Version

8.3

### Operating System

Linux, MacOS, Windows

### Description

This is important... the `418` status code has the wrong description.

### Steps to Reproduce

Look at the Http status code 418.

**Comment by brendt** [comment]
What's wrong with it?

**Comment by aidan-casey** [comment]
Spec says "I'm a Teapot." Also, on two or three enum values, their factory method is _not_ covered by tests and actually is failing.

I saw this by running coverage on unit tests, not the integration tests. 😛🙃
