### ISSUE TITLE
Name collision between Migration

### ISSUE THREAD

**Issue by brendt** [tempestphp/tempest-framework#788]
There's both the `Migration` interface and the `Migration` model. We should rename the `Migration` model so that there's no naming collision

**Comment by kevinfrom** [comment]
Since the `Migration` interface should return a `QueryStatement` on `up` and `down`, should we rename the `Migration` interface to `DatabaseMigration` and leave the model be?

**Comment by brendt** [comment]
Hah, that's a great idea!

**Comment by kevinfrom** [comment]
I'll make a PR once I'm home :)

**Comment by brendt** [comment]
Fixed with #848
