### ISSUE TITLE
Refactor Route attribute

### ISSUE THREAD

**Issue by brendt** [tempestphp/tempest-framework#789]
People can use `Route` directly, as well as `Get`, `Post`, … 

In order to make custom route attributes, we allow people to extend from `Route`. This is very inconsistent with the rest of the framework. I propose to make `Route` an interface, provide an `IsRoute` trait, and to not have `Route` available as an attribute anymore.

**Comment by blackshadev** [comment]
I like to do this. Seems fun and easy.
