### ISSUE TITLE
[Feature Request]: Support swoole

### ISSUE THREAD

**Issue by sinhnv1991** [tempestphp/tempest-framework#794]
### Description

I think support swoole into tempest soon to make tempest stronger
example when run a query: 
Book::enableConcurrently()->with(['author', 'tags'])->paginate();
we can use swoole run multiple concurrently get data author, tags after run get books and extract list id of books;
If query relations or nested relations into one query and map to model becomes complicated, we can think of prefixing the column name of each model like Laravel make when query many-to-many relationships by pivot using prefixing pivot_xxx before the field name or using swole is a good way to optimize speed

### Benefits

Open Swoole enhances the efficiency of PHP applications

**Comment by brendt** [comment]
I definitely agree it would add value, but it's something we won't be able to look into anytime soon. We'll reconsider this after 1.0 though
