### ISSUE TITLE
Reconsider DBAL and migration implementation

### ISSUE THREAD

**Issue by brendt** [tempestphp/tempest-framework#80]
The current implementation lacks a lot of things. We're considering whether switching to `nette/database` might be the wiser move if we're working towards Tempest 1.0

Up for discussion:

After some consideration, I don't think it makes sense to try and build a TableBuilder from scratch that supports multiple SQL grammars. Rather, let's just use plain SQL (like Doctrine does), it makes it so that we can get rid of much code, and on top of that embraces SQL in full.

There's the argument that this leads to not being able to use different databases between local and production environment. I'd actually say that's a good thing. There _are_ fundamental differences between different databases, and using a different one locally might actually lead to bugs in production that you hadn't noticed before. Any substential project of mine that grew to a certain size actually switched to using the same database in all environments, because of these kinds of problems.

If we switch to raw SQL for migrations though, there's much less need for a DBAL — as far as I can tell right now — because we don't have to worry about differences between databases. In that case, it might be good just to stick with PDO for now.

**Comment by brendt** [comment]
How about we use SQL instead of `TableBuilder`? see stream

**Comment by aidan-casey** [comment]
The biggest challenges I can see to using SQL directly are:

1. Losing the ability to support multiple database types (whether for testing, the ability to give client deployments flexibility, etc.)

2. Losing the ability to automatically generate differential migration scripts which save the developer some time to not think about it.

I don't mind writing SQL, it makes me reminiscent of the early 2000's, but it's worth noting those deficiencies in that approach.

**Comment by devnix** [comment]
You can offer a separate package to configure into the container a DBAL with your main connection already configured, and optionally use it. Anyway, I guess you can always choose to manually depend on a query builder by adding the service yourself in your project.

**Comment by brendt** [comment]
I asked the question on Twitter as well: https://twitter.com/brendt_gd/status/1760231282133319823

The argument that made most sense to me is this:

> The second one is great if you want to support multiple databases. But you will always play the catchup-game to add stuff thats missing. Which won't be the case with the 1st approach.
>
> And especially if you support more databases than MySQL the catchup game is hard. There are a ton of features one could use with e.g. PostgreSQL.

I think the wisest decision right now it to only support plain SQL. As @devnix points out, adding some kind of grammar-specific query builder in the future would be trivial (to plug in, not to build), people could even already do that today if they want to. 

I went ahead and made the necessary changes: 

- https://github.com/tempestphp/tempest-framework/commit/6da9ba652d16247ff19cc6fefdec9bb213f2cb33
- https://github.com/tempestphp/tempest-framework/commit/e482372d167a9fe30c42b206e1eab28fe26eae6f

With the current implementation, I don't see a huge need for a DBAL, since adding support for more drivers means implementing one very simple `Driver` class. There's currently nothing else we'd gain from switching to a third party DBAL. This could change in the future, in which case we can use the `Database` class (which currently wraps `PDO`) as an entry point. 

I'm gonna close this issue for now, but if anyone has any followup thoughts: don't hesitate to comment.

**Comment by aidan-casey** [comment]
@brendt what are the implications of this for the ORM module? Doesn't this necessarily move us toward fully repository?

A first party package in the future is not a bad idea in the sense that we could start this way for v1 and easily add it as a non-breaking change if needed.

**Comment by brendt** [comment]
> @brendt what are the implications of this for the ORM module? Doesn't this necessarily move us toward fully repository?

None :) The Query class still allows for [executing itself](https://github.com/tempestphp/tempest-framework/blob/main/src/Database/Query.php#L18) by using service location. (I know, but it's super convenient in this case).

The ORM works by mapping model classes to queries and vice-versa; it's totally oblivious to the underlying Database layer — separation of concerns FTW!

I refactored the whole DBAL layer in less than an hour, and everything works as expected.

**Comment by mokhosh** [comment]
what if we create a thin optional layer of abstraction to make 90% of normal stuff super easy, and still allow them to bypass the builder step and provide raw sql, if they don't care about swaping dbms' and other goodies?

**Comment by brendt** [comment]
@mokhosh Ik think this is a good idea, and it's entirely possible to do so because migrations now return a `Query` object. We can include a simple query builder within this object.

The big issue for me is supporting different dialects; there even are differences between MySQL and SQLite — how will we handle those? I'm gonna create a new issue to discuss this specifically: #103
