### ISSUE TITLE
Undefined property tagName

### ISSUE THREAD

**Issue by yassiNebeL** [tempestphp/tempest-framework#801]
We need to check the node before accessing the tagName property, because Dom\Comment have not.

To reproduce it, just hit the /form route!

**Comment by innocenzi** [comment]
Was https://github.com/tempestphp/tempest-framework/pull/792 not a fix for this?

**Comment by yassiNebeL** [comment]
Hey @innocenzi ,

the #803 is ready to merge!

**Comment by innocenzi** [comment]
You can create PRs without associated issues. We just need time to get to them.
