### ISSUE TITLE
[Feature Request]: add better fallback to enum command parameter

### ISSUE THREAD

**Issue by gturpin-dev** [tempestphp/tempest-framework#807]
### Description

Hey 👋 

I wanted to improve the console command fallback system.
I mean, currently in case we have a command argument that's an enum, if we don't provide it, Tempest will ask us for the value as a plain string without giving more indications.

![Capture d'écran 2024-12-04 162618](https://github.com/user-attachments/assets/f41acb1c-0d6c-4538-b4e8-a12bc4caec23)

Then, I wonder if we could provide a better DX on it.
So my thought is that we can give the beautiful Tempest select component with all Enum cases to the user.

WDYT ?

If you are ok, I can give it a look

### Benefits

Provide a better DX for console commands

**Comment by aidan-casey** [comment]
This makes total sense, @gturpin-dev!

**Comment by innocenzi** [comment]
@gturpin-dev do you mind if I assign this to me? I found a few issues with the choice components when working with enums, so I'll fix it along with implementing support for this

**Comment by gturpin-dev** [comment]
@innocenzi No problem, you can do it then 😄 
If you want to discuss it if not clear, we can do that on discord 😄
