### ISSUE TITLE
Acronym Inconsistencies

### ISSUE THREAD

**Issue by aidan-casey** [tempestphp/tempest-framework#96]
@brendt - I just noticed we have some inconsistencies with our acronyms, some of them my fault. For example:

- `Uuid`
- `ORM`
- `MACAddress`
- `Regex`

I think I am of the mind to capitalize class names where it would normally be capitalized. So these become:

- `UUID`
- `ORM`
- `MACAddress`
- `RegEx`

Any problem with this line of thinking?

**Comment by brendt** [comment]
Ah, yes. There's actually some kind of convention about this. I actually think it comes from .NET: https://learn.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/ms229043(v=vs.100)?redirectedfrom=MSDN

> Casing of acronyms depends on the length of the acronym. All acronyms are at least two characters long. For the purposes of these guidelines, if an acronym is exactly two characters, it is considered a short acronym. An acronym of three or more characters is a long acronym.

I don't have a strong opinion about it 🤷‍♂️

Whatever we choose, we should document it

**Comment by aidan-casey** [comment]
I can get on board with this. Let's adopt the following per that article:

**Do capitalize both characters of two-character acronyms, except the first word of a camel-cased identifier.**

A property named DBRate is an example of a short acronym (DB) used as the first word of a Pascal-cased identifier. A parameter named ioChannel is an example of a short acronym (IO) used as the first word of a camel-cased identifier.

**Do capitalize only the first character of acronyms with three or more characters, except the first word of a camel-cased identifier.**

A class named XmlWriter is an example of a long acronym used as the first word of a Pascal-cased identifier. A parameter named htmlReader is an example of a long acronym used as the first word of a camel-cased identifier.

**Do not capitalize any of the characters of any acronyms, whatever their length, at the beginning of a camel-cased identifier.**

A parameter named xmlStream is an example of a long acronym (xml) used as the first word of a camel-cased identifier. A parameter named dbServerName is an example of a short acronym (db) used as the first word of a camel-cased identifier.

---

Cleaning up the existing classes and updating the contributing file with that will close this issue.

**Comment by brendt** [comment]
Seems good! Although I'm not sure I understand the first one 🤔 are camel-case identifiers things like properties, and Pascal-cased ones are eg. classes? So

`PDO` is the class name, but `$pdo` is the variable name?

**Comment by aidan-casey** [comment]
Close! As a property it'd be `pdo` as a class it'd be `Pdo` since it is three characters.

**Comment by brendt** [comment]
Oh, why two instead of three?

**Comment by aidan-casey** [comment]
_Do capitalize both characters of two-character acronyms, except the first word of a camel-cased identifier._

_ Do capitalize only the first character of acronyms with three or more characters, except the first word of a camel-cased identifier._

`Pdo` would be a three letter acronym while `IP` would be a two letter acronym?

**Comment by aidan-casey** [comment]
Because Bill Gates told me so!

In all seriousness, I'm fine adjusting that, but I think you just want to maintain all-caps `ORM`. 🙃

If someone happens to pick this off before me, just adjust the above accordingly to _four_ letter acronyms being the point that only the first letter is capitalized.

**Comment by aidan-casey** [comment]
Closed by #121.
