### ISSUE TITLE
Modularization Cleanup

### ISSUE THREAD

**Issue by aidan-casey** [tempestphp/tempest-framework#97]
After further breaking out into Tempest modules, we still have a few lingering items:

- Discovery classes
- Default configurations
- Console commands

@brendt - To me, it feels like discovery classes and console commands can get moved to their appropriate modules. The default configurations feel like they should get moved to the application skeleton. Any disagreement?

On another note, is the reason to have an application skeleton in the framework package purely for testing / package development?

**Comment by brendt** [comment]
> Any disagreement

Yes.

😁

I agree on discovery and console commands moving to separate modules, go ahead ✅ 

Config however is another story. The config files in `src` are the default files, I don't want the skeleton to have them, as they would clutter a clean project, and would only contain the default setup. So we need to keep them in `src`

> On another note, is the reason to have an application skeleton in the framework package purely for testing / package development?

Yeah this is just old code, it should be moved to `tests`: #104

**Comment by aidan-casey** [comment]
> Yes.

![](https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExMnNzbWloczU5bWthMGZmczBtMXVoYmM3MTZpZG92NHUwN3c2YXJseCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/kyrd72DC2Iwfu/giphy.gif)

> Config however is another story.

Yeah, I kind of expected that. Just wish we had a cleaner way to set that up. 😛 

> Yeah this is just old code, it should be moved to `tests`

👍🏼

**Comment by brendt** [comment]
> Yeah, I kind of expected that. Just wish we had a cleaner way to set that up. 😛

I don't mind changing our conventions about it, I now just followed what Laravel did because that's what I knew. I'm open to alternatives :)

**Comment by brendt** [comment]
Let's close this one for now. I plan on doing a very critical look at the whole framework once we're nearing 1.0, and we can reconsider configs if necessary then.
